import React, { createContext, useContext, useState } from "react";

type Lang = "es" | "en";

export const translations = {
  es: {
    dashboard: "Dashboard",
    dashboardDesc: "Resumen general de tus equipos",
    searchPeople: "Buscar personas...",
    members: "Miembros",
    absent: "Ausentes",
    upcoming: "Próximas",
    activeHandovers: "Handovers activos",
    noActiveHandovers: "No hay handovers activos en este momento.",
    navigation: "Navegación",
    absences: "Ausencias",
    handovers: "Handovers",
    bugs: "Bugs",
    bugsPageTitle: "Bugs",
    bugsPageDescription: "Bugs obtenidos desde una query existente de Azure DevOps.",
    bugsColumnId: "ID",
    bugsColumnTitle: "Título",
    bugsColumnAssignee: "Asignado a",
    bugsColumnState: "Estado",
    bugsColumnIteration: "Iteración",
    bugsColumnArea: "Área",
    bugsColumnSeverity: "Severidad",
    bugsFilterSearch: "Buscar por título, ID o persona...",
    bugsFilterAssignee: "Asignado",
    bugsFilterState: "Estado",
    bugsFilterSeverity: "Severidad",
    bugsFilterIteration: "Iteración",
    bugsFilterAll: "Todos",
    bugsRefresh: "Refrescar",
    bugsCount: "bugs",
    bugsEmpty: "La query no devolvió ningún bug.",
    bugsLoading: "Cargando bugs desde Azure DevOps...",
    bugsNoConnection: "Aún no has configurado la conexión con Azure DevOps.",
    bugsNoIterationConfigured: "Configura al menos una iteración en los ajustes de Azure DevOps para listar los bugs.",
    bugsIterationPathsLabel: "Iteraciones configuradas",
    bugsIterationPathsNone: "Ninguna iteración configurada",
    bugsOpenSettings: "Abrir ajustes",
    bugsUnassigned: "Sin asignar",
    bugDetailPriority: "Prioridad",
    bugDetailCreatedBy: "Creado por",
    bugDetailCreated: "Creado",
    bugDetailChanged: "Modificado",
    bugDetailTags: "Etiquetas",
    bugDetailDescription: "Descripción",
    bugDetailNoDescription: "Sin descripción.",
    bugDetailReproSteps: "Pasos para reproducir",
    bugDetailLinks: "Enlaces y relaciones",
    bugDetailNoLinks: "Sin enlaces.",
    bugDetailOpenInAdo: "Abrir en Azure DevOps",
    features: "Features",
    tasks: "Tareas",
    workload: "Carga & Capacidad",
    pulse: "Pulse",
    featuresAndTasks: "Features & Tareas",
    team: "Equipo",
    // Team page
    teamNotFound: "Equipo no encontrado",
    add: "Añadir",
    newMember: "Nuevo miembro",
    name: "Nombre",
    role: "Rol",
    search: "Buscar...",
    all: "Todos",
    allTeams: "Todos los equipos",
    allTypes: "Todos los tipos",
    available: "Disponibles",
    vacation: "Vacaciones",
    sickLeave: "Baja",
    workTravel: "Viaje de trabajo",
    otherProject: "Otro proyecto",
    parentalLeave: "Baja parental",
    workTopics: "Temas de trabajo",
    addTopic: "Añadir tema",
    topicName: "Nombre del tema...",
    description: "Descripción",
    descPlaceholder: "Descripción...",
    status: "Estado",
    pending: "Pendiente",
    inProgress: "En progreso",
    blocked: "Bloqueado",
    completed: "Completado",
    save: "Guardar",
    create: "Crear",
    noTopics: "Sin temas asignados",
    deleteMember: "Eliminar miembro",
    errSelectMember: "Selecciona al menos un miembro",
    errInvalidMaxCapacity: "Capacidad máxima inválida",
    errInvalidBaseCapacity: "Capacidad base inválida",
    errBaseGtMax: "La capacidad base no puede ser mayor que la capacidad máxima",
    errBulkConflict: "Para algunos miembros, la nueva configuración hace que la capacidad base supere a la máxima. Revisa los valores.",
    capacityUpdated: "Capacidad actualizada para {count} miembros",
    errNameMinLength: "El nombre debe tener al menos 2 caracteres",
    errRoleMinLength: "El rol debe tener al menos 2 caracteres",
    errMaxLtBase: "La capacidad máxima no puede ser menor que la base",
    errBaseGtMaxSingle: "La capacidad base no puede ser mayor que la máxima",
    resetCapacityConfirmTitle: "¿Restablecer capacidad?",
    resetCapacityConfirmDesc: "¿Estás seguro de que quieres restablecer la capacidad de {name} a los valores por defecto (Máx: 40h, Base: 32h)?",
    resetCapacity: "Restablecer",
    undo: "Deshacer",
    capacityResetSuccess: "Capacidad restablecida",
    capacityConfig: "Configuración de Capacidad",
    maxCapacity: "Capacidad Máxima (h/sem)",
    baseCapacity: "Capacidad Base (h/sem)",
    // Absences page
    absencesDesc: "Gestión de vacaciones y bajas",
    exportCsv: "Exportar CSV",
    newAbsence: "Nueva ausencia",
    editAbsence: "Editar ausencia",
    updateAbsence: "Actualizar ausencia",
    registerAbsence: "Registrar ausencia",
    person: "Persona",
    select: "Seleccionar...",
    type: "Tipo",
    start: "Inicio",
    end: "Fin",
    date: "Fecha",
    register: "Registrar",
    timeline: "Timeline",
    list: "Lista",
    noAbsencesMonth: "Sin ausencias este mes",
    noAbsences: "No hay ausencias registradas.",
    totalDays: "días totales",
    days: "días",
    // Handovers page
    handoversDesc: "Gestión de traspasos de trabajo",
    filterByDate: "Filtrar por fecha",
    from: "Desde",
    to: "Hasta",
    clearFilter: "Limpiar filtro",
    createHandover: "Crear handover",
    newHandover: "Nuevo handover",
    absentPerson: "Persona ausente",
    covers: "Cubre",
    topicsToTransfer: "Temas a traspasar",
    notes: "Notas",
    notesPlaceholder: "Instrucciones para el handover...",
    noHandovers: "No hay handovers creados.",
    editHandover: "Editar handover",
    updateHandover: "Actualizar handover",
    created: "Creado",
    handoverDetail: "Detalle del handover",
    absenceType: "Tipo",
    absencePeriod: "Período de ausencia",
    topicCount: "temas",
    deleteHandoverTitle: "¿Eliminar handover?",
    deleteHandoverDesc: "Esta acción no se puede deshacer. El handover será eliminado permanentemente.",
    deleteAbsenceTitle: "¿Eliminar ausencia?",
    deleteAbsenceDesc: "Esta acción no se puede deshacer. La ausencia será eliminada permanentemente.",
    handoverSelectAbsent: "Selecciona la persona ausente",
    handoverSelectCover: "Selecciona quién cubre",
    handoverSelectTopics: "Selecciona al menos un tema",
    noTopicsAvailable: "Esta persona no tiene temas asignados. Puedes continuar sin seleccionar ninguno.",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmMove: "¿Mover miembro?",
    confirmMoveDesc: "¿Mover a {name} al equipo {team}?",
    confirmDelete: "Eliminar",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Capacidad del equipo",
    analyticsHandoverRate: "Tasa de handover",
    analyticsActiveAbsences: "Ausencias activas",
    analyticsActive: "activos",
    analyticsCurrently: "actualmente",
    analyticsTeamCapacity: "Capacidad por equipo",
    analyticsAbsenceType: "Tipo de ausencia",
    analyticsAbsenceTrend: "Tendencia de ausencias (21 días)",
    analyticsNoData: "Sin datos disponibles",
    analyticsNoAbsences: "Sin ausencias activas",
    // Notifications
    notifTitle: "Notificaciones",
    notifCritical: "críticas",
    notifWarnings: "avisos",
    notifEmpty: "Todo en orden, sin alertas",
    notifNoHandover: "Ausencia sin handover",
    notifNoHandoverDesc: "{name} está ausente sin ningún handover asignado",
    notifUpcomingNoHandover: "Ausencia próxima sin handover",
    notifUpcomingNoHandoverDesc: "{name} se ausenta el {date} y no tiene handover",
    notifCoverageGap: "Brecha de cobertura",
    notifCoverageGapDesc: "{team}: {absent} de {total} miembros ausentes",
    notifUncoveredTopics: "Temas sin cobertura",
    notifUncoveredTopicsDesc: "{count} temas de {name} sin cubrir durante su ausencia",
    // Import absences
    importAbsences: "Importar ausencias",
    importDropzone: "Arrastra un archivo o haz clic para seleccionar",
    importFormats: "CSV, XLSX o XLS",
    importRows: "filas detectadas",
    importChangeFile: "Cambiar archivo",
    importSelectColumn: "Seleccionar columna",
    importPreviewSample: "Vista previa de las primeras filas:",
    importValidate: "Validar datos",
    importValid: "válidas",
    importInvalid: "con errores",
    importBackToMapping: "Volver al mapeo",
    importConfirm: "Importar ausencias",
    importSuccess: "ausencias importadas",
    importParseError: "Error al leer el archivo",
    importEmpty: "El archivo está vacío",
    importUnsupportedFormat: "Formato no soportado. Usa CSV o XLSX",
    importErrNoName: "Sin nombre",
    importErrMemberNotFound: "Miembro no encontrado",
    importErrInvalidType: "Tipo inválido",
    importErrInvalidStart: "Fecha inicio inválida",
    importErrInvalidEnd: "Fecha fin inválida",
    importErrDateOrder: "Inicio posterior al fin",
    // Invent format
    importModeGeneric: "Genérico (CSV / Excel)",
    importModeInvent: "Formato Invent",
    importInventDropzone: "Arrastra el fichero Absent.xlsx exportado de Invent",
    importInventFormats: "Solo .xlsx",
    importAutoDetectedInvent: "Formato ROSEN detectado — cambiado al parser Invent",
    importInventSummary: "{imported} ausencias listas · {unmatched} sin coincidencia · {skipped} filas descartadas",
    importInventNoLogin: "Login no encontrado",
    importInventLoginCol: "Login",
    importInventMemberCol: "Miembro",
    importResultTitle: "Última importación",
    importResultCreated: "ausencias creadas",
    importResultSkipped: "filas ignoradas",
    importResultUnmatched: "logins sin coincidencia",
    importResultDismiss: "Ocultar resumen",
    importValidationFailed: "El archivo no coincide con el formato esperado",
    importValidationHint: "Encabezados esperados: A=Work date, C=Person, D=Duration, E=Activity kind. Fechas como YYYY-MM-DD, DD/MM/YYYY o celda de fecha de Excel.",
    importUnmatchedRangesLabel: "rangos pendientes",
    importAssignToMember: "Asignar a miembro…",
    // JSON import (backup)
    importModeJson: "JSON (backup)",
    importJsonDropzone: "Arrastra el fichero JSON exportado",
    importJsonFormats: "Solo .json — se importan únicamente las ausencias",
    importJsonNoAbsences: "El archivo no contiene ausencias",
    importJsonMemberNotFound: "Miembro no encontrado",
    importJsonDuplicate: "Duplicada",
    importJsonStatusOk: "OK",
    importJsonSummary: "{ok} nuevas · {dup} duplicadas · {missing} sin miembro",
    loginName: "Login de usuario",
    loginNamePlaceholder: "ej. jsmith",
    // Azure DevOps / TFS
    importTfsTeamMembers: "Importar de ADO",
    importTfsTeamMembersTitle: "Importar miembros desde Azure DevOps",
    importTfsTeamMembersDesc: "Selecciona a quiénes quieres añadir a este equipo de Lovable.",
    importTfsConfigureAlert: "Para importar, primero debes configurar la conexión y seleccionar un equipo en los Ajustes de Azure DevOps.",
    importTfsNoMembers: "No se encontraron miembros en el equipo de ADO, o no se pudo cargar la lista.",
    importTfsDuplicateTooltip: "Ya existe en el equipo actual",
    importTfsImportCount: "Añadir {count} miembro(s)",
    importTfsSuccess: "Se han añadido {count} miembro(s)",
    importTfsConfigureTitle: "Configuración incompleta",
    importTfsConfigureHint1: "Ve a Ajustes › Azure DevOps y completa servidor, colección, proyecto, PAT y equipo.",
    importTfsErrCorsTitle: "Sin acceso al TFS (¿VPN de ROSEN activa?)",
    importTfsErrCorsHint1: "Conéctate a la VPN de ROSEN o usa un equipo dentro de la red corporativa antes de importar. El TFS on-prem no es alcanzable desde internet.",
    importTfsErrCorsHint2: "Si ya estás en la red, comprueba abriendo la URL del TFS en otra pestaña; si carga ahí, es un problema de CORS del TFS (avisa a IT).",
    importTfsErrMixedTitle: "Contenido mixto bloqueado",
    importTfsErrMixedHint1: "Esta app va por HTTPS pero el servidor TFS configurado usa HTTP. Usa una URL https:// en los ajustes.",
    importTfsErrTimeoutTitle: "Tiempo de espera agotado",
    importTfsErrTimeoutHint1: "El servidor TFS no respondió a tiempo. Verifica VPN/red interna y que la URL del servidor sea accesible.",
    importTfsErrTimeoutHint2: "Prueba la conexión desde Ajustes › Azure DevOps para confirmar la conectividad.",
    importTfsErrUnauthorizedTitle: "PAT no válido o caducado (401)",
    importTfsErrUnauthorizedHint1: "Regenera el Personal Access Token en Azure DevOps y guárdalo de nuevo en Ajustes.",
    importTfsErrUnauthorizedHint2: "Comprueba que el PAT no ha caducado ni ha sido revocado.",
    importTfsErrForbiddenTitle: "Permisos insuficientes (403)",
    importTfsErrForbiddenHint1: "El PAT necesita los scopes: Project & Team (Read), Work Items (Read).",
    importTfsErrForbiddenHint2: "Verifica que tu usuario tenga acceso al equipo seleccionado.",
    importTfsErrNotFoundTitle: "Equipo o proyecto no encontrado (404)",
    importTfsErrNotFoundHint1: "Revisa que la colección, proyecto y equipo en Ajustes coinciden exactamente con los de TFS.",
    importTfsErrNotFoundHint2: "Si renombraron el equipo, vuelve a seleccionarlo en Ajustes › Azure DevOps.",
    importTfsErrHttpTitle: "Error HTTP {status}",
    importTfsErrHttpHint1: "El servidor TFS respondió con un error. Reintenta o revisa la configuración.",
    importTfsErrUnknownTitle: "No se pudo importar",
    importTfsErrUnknownHint1: "Reintenta. Si persiste, prueba la conexión desde Ajustes › Azure DevOps.",
    importTfsErrShowDetail: "Ver detalles técnicos",
    importTfsHistoryTitle: "Historial de importaciones",
    importTfsHistoryCount: "{count} entradas",
    importTfsHistoryAdded: "{count} miembro(s) añadidos",
    importTfsHistoryReview: "Revisar",
    importTfsHistoryReviewTitle: "Importación realizada",
    importTfsHistoryEmpty: "No se registraron miembros para esta importación.",
    importTfsRoleLabel: "Rol asignado a los miembros importados",
    importTfsRoleCustom: "Personalizado…",
    importTfsRolePlaceholder: "Escribe un rol…",
    importTfsRoleRequired: "Indica un rol antes de importar",
    adoTitle: "Azure DevOps / TFS",
    adoDesc: "Conecta con Azure DevOps Server (TFS on-premise) o Azure DevOps cloud",
    adoConnection: "Conexión",
    adoConnectionDesc: "Introduce los datos de tu servidor TFS y un PAT con permisos de lectura",
    adoServerUrl: "URL del servidor",
    adoServerUrlHint: "Ej. https://tfs.empresa.net/tfs (sin la colección)",
    adoCollection: "Colección",
    adoCollectionHint: "Nombre de la colección de proyectos en TFS (ej. RNDCollection)",
    adoOrganization: "Organización (cloud)",
    adoOrgHint: "Solo para Azure DevOps cloud (dev.azure.com/{org}). Déjalo vacío para TFS on-premise.",
    adoProject: "Proyecto",
    adoTeam: "Equipo (opcional)",
    adoTeamHint: "Filtra por equipo dentro del proyecto, si aplica",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Necesita permisos: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Probar conexión",
    adoConnectionOk: "Conexión exitosa",
    adoConnectionFailed: "Error de conexión",
    adoFillAllFields: "Completa los campos obligatorios (URL, colección, proyecto y PAT)",
    adoLoginRequired: "Inicia sesión para continuar",
    adoTestFirst: "Prueba la conexión primero",
    adoSyncSettings: "Sincronización",
    adoAutoSync: "Sincronización automática",
    adoAutoSyncDesc: "Sincronizar periódicamente con TFS",
    adoSyncInterval: "Intervalo",
    adoMinutes: "minutos",
    adoHour: "hora",
    adoLastSync: "Última sincronización",
    adoSaveSettings: "Guardar configuración",
    adoUpdateSettings: "Actualizar configuración",
    adoSettingsSaved: "Configuración guardada",
    adoSettingsDeleted: "Configuración eliminada",
    adoDisconnect: "Desconectar",
    adoNetworkWarningTitle: "Requiere acceso a la red corporativa",
    adoNetworkWarningBody: "La conexión se hace directamente desde tu navegador al servidor TFS. Necesitas estar en la red interna o conectado por VPN, y el TFS debe permitir CORS desde el origen de esta app.",
    // Auth
    authLogin: "Iniciar sesión",
    authSignup: "Crear cuenta",
    authPassword: "Contraseña",
    authSubtitle: "Gestión de handovers y equipos",
    authNamePlaceholder: "Tu nombre",
    authLoginSuccess: "Sesión iniciada",
    authSignupSuccess: "Cuenta creada correctamente",
    authPasswordMin: "La contraseña debe tener al menos 6 caracteres",
    authForgotPassword: "¿Olvidaste tu contraseña?",
    authResetPassword: "Restablecer contraseña",
    authResetDesc: "Introduce tu email y te enviaremos un enlace",
    authSendReset: "Enviar enlace",
    authResetSent: "Enlace enviado, revisa tu bandeja de entrada",
    authBackToLogin: "Volver al inicio de sesión",
    authNewPassword: "Nueva contraseña",
    authNewPasswordDesc: "Introduce tu nueva contraseña",
    authUpdatePassword: "Actualizar contraseña",
    authPasswordUpdated: "Contraseña actualizada correctamente",
    authInvalidResetLink: "Enlace de restablecimiento no válido o expirado",
    authLogout: "Cerrar sesión",
    bulkCapacityEditTitle: "Edición en Bloque de Capacidades",
    preloadingAreas: "Precargando áreas…",
    usingCache: "Usando caché",
    statusDistribution: "Distribución por estado",
    statusDistributionDesc: "Qué se está ejecutando ahora mismo",
    topTasks: "Top {count} con más tareas",
    cache: "Caché",
    moreTasks: "Más tareas",
    lessTasks: "Menos tareas",
    defaultSort: "Por defecto",
    sortBy: "Ordenar por",
    title: "Título",
    noArea: "(sin área)",
    noIteration: "(sin iteración)",
    noTitle: "(sin título)",
    outOfScopeHidden: "Elementos fuera del alcance ocultos automáticamente",
    errTeamAreasUpdate: "No se pudo actualizar la lista de áreas del equipo. Se está usando la última versión en caché.",
    errPeopleUpdate: "No se pudo actualizar la lista de personas. Se está mostrando el último listado en caché.",
    errIncompleteAdoConfig: "Configuración de Azure DevOps incompleta. Mostrando datos locales.",
    hideHandover: "Ocultar handover",
    addHandover: "Añadir handover",
    tasksSubtitle: "Trabajo asignado por persona, abierto y en progreso.",
    featuresSubtitle: "Iniciativas del proyecto y su progreso global.",
    generalOverview: "Visión general del trabajo en curso del proyecto.",
    workloadSubtitle: "Disponibilidad y carga de trabajo agrupada por semana (solo tareas In Progress).",
    workloadSubtitleAll: "Disponibilidad y carga de trabajo agrupada por semana (todas las tareas activas).",
    taskDetailInProgress: "Detalle de Tareas (In Progress) - {name}",
    taskDetailAll: "Detalle de Tareas (Todas) - {name}",
    inProgressTasksCount: "{count} In Progress",
    allTasksCount: "{count} Tareas",
    onlyInProgress: "Solo In Progress",
    allTasks: "Todas las tareas",
    addTeam: "Añadir equipo",
    ongoing: "En curso",
    upcomingStatus: "Próximo",
    checkHowTo: "Cómo verificar:",
    checkCorsDetails: "pulsa Probar conexión y comprueba que la petición OPTIONS (preflight) recibe",
    adoAreas: "Áreas (Features y Tareas)",
    errFieldsDiagnostics: "Corrige los campos marcados antes de ejecutar el diagnóstico.",
    errDiagnostics: "Error en diagnóstico",
    errFieldsConnection: "Corrige los campos marcados antes de probar la conexión.",
    errAdoProjects: "Introduce servidor, colección y PAT para listar proyectos.",
    errAdoTeams: "Introduce servidor, colección, proyecto y PAT para listar equipos.",
    adoSelectAreas: "Selecciona una o varias áreas…",
    adoNoAreasFound: "No se encontraron áreas para este proyecto.",
    errAdoLoadAreas: "Configura servidor, colección, proyecto y PAT para cargar las áreas.",
    errAdoLoadIterations: "Configura servidor, colección, proyecto y PAT para cargar las iteraciones.",
    errImportInvalidJson: "Error al importar: archivo JSON inválido",
    confirmImportOverwrite: "¿Estás seguro? Esto sobrescribirá todos los datos actuales con los del archivo seleccionado.",
    writeSomething: "Escribe algo",
    max2000Chars: "Máximo 2000 caracteres",
    invalidUrl: "URL inválida",
    urlTooLong: "URL demasiado larga",
    mustBeLoggedIn: "Debes iniciar sesión",
    anonymous: "Anónimo",
    noteAdded: "Anotación añadida",
    noMatchingItems: "Ningún elemento coincide con lo escrito.",
    // Not found
    pageNotFound: "Oops! Página no encontrada",
    returnHome: "Volver al inicio",
    workloadAndCapacity: "Carga de Trabajo y Disponibilidad",
    allMembers: "Todos los miembros",
    selectedCount: "{count} seleccionados",
    searchMember: "Buscar miembro...",
    noResults: "No hay resultados.",
    weeks: "Semanas",
    nWeeks: "{count} Semanas",
    member: "Miembro",
    weekDate: "Semana {date}",
    effortHours: "Esfuerzo: {hours}h",
    noTasksThisWeek: "No hay tareas asignadas para esta semana.",
    filtersApplied: "Filtros aplicados a las consultas de Features y Tareas. Cámbialos en Ajustes › Azure DevOps.",
    iterationsTasks: "Iteraciones (Tareas)",
    featureCount: "{count} feature",
    featuresCount: "{count} features",
    taskCount: "{count} tarea",
    tasksCountPlural: "{count} tareas",
    featuresOutOfArea: "Features fuera del área ({count})",
    tasksOutOfArea: "Tareas fuera del área ({count})",
    tasksOutOfIteration: "Tareas fuera de la iteración ({count})",
    projectFeatures: "Features del proyecto",
    featureProgress: "Progreso por feature con tareas asociadas",
    noFeaturesToShow: "No hay features para mostrar.",
    tasksRatio: "{done} / {total} tareas",
    loadPerPerson: "Carga por persona",
    tasksPerPerson: "Tareas por persona",
    fetchAreasError: "No se pudieron leer las áreas del equipo: {error}",
    unassigned: "Sin asignar",
    effectiveScope: "Alcance efectivo",
    resultWithScope: "Resultado con este alcance",
    noCustomScope: "No hay alcance personalizado en Ajustes; se usan los valores por defecto del equipo RODAT.",
    showingXofYFeatures: "Mostrando {x} de {y} features",
    showingXofYTasks: "Mostrando {x} de {y} tareas",
    excludedOutOfAreaFeatures: "Excluidas: {count} features fuera del área,",
    excludedOutOfAreaTasks: " {count} tareas fuera del área,",
    excludedOutOfIterTasks: " {count} tareas fuera de la iteración.",
    viewHiddenAudit: "Ver auditoría de elementos ocultos",
    area: "Área",
    iterationTasks: "Iteración (tareas)",
    expectedUnder: "Esperado bajo {paths}",
    copyLinkTask: "Copiar enlace de la tarea {id}",
    copyLinkFeature: "Copiar enlace de la feature {id}",
    linkCopied: "Enlace de la {type} #{id} copiado",
    linkCopyFailed: "No se pudo copiar el enlace",
    workDistribution: "Distribución del trabajo por persona — solo abiertas y en progreso.",
    personCount: "{count} persona",
    personsCount: "{count} personas",
    filtering: "filtrando",
    inProgressPlural: "en progreso",
    pendingPlural: "pendientes",
    wipBadgeLabel: "WIP",
    wipBadgeTooltip: "{n} tareas/bugs en curso o pendientes",
    tasksViewFilterHint: "Mostrando tareas abiertas / en curso y bugs cerrados en los últimos 10 días.",
    wipDetailsTitle: "Carga actual · {person}",
    wipDetailsDescription: "{n} tareas y bugs contados en el WIP.",
    wipDetailsEmpty: "No hay elementos en curso.",
    wipTooltipFormulaAll: "Cuenta tasks y bugs en estado Open o In Progress.",
    wipTooltipFormulaTasks: "Cuenta tasks y bugs en estado Open o In Progress.",
    wipTooltipClickHint: "Haz clic para ver el detalle.",
    wipBreakdownActiveTasks: "Tasks en curso",
    wipBreakdownActiveBugs: "Bugs en curso",
    wipBreakdownPendingTasks: "Tasks pendientes",
    wipBreakdownPendingBugs: "Bugs pendientes",
    blockedPlural: "bloqueadas",
    completedPlural: "completadas",
    resolvedPlural: "resueltas",
    closedPlural: "cerradas",
    confirmChangesBeforeApply: "Confirmar cambios antes de aplicar",
    unappliedChanges: "Cambios sin aplicar",
    discard: "Descartar",
    apply: "Aplicar",
    viewByPerson: "Vista por persona",
    viewFlatList: "Ver listado plano",
    showingMaxOf: "Mostrando {max} de {total} tareas — afina los filtros para ver más.",
    noPersonsMatching: "No hay personas con tareas que coincidan con los filtros actuales.",
    noTasksForTeam: "No hay tareas asignadas a personas del equipo {team}.",
    noTasksForPerson: "{person} no tiene tareas que coincidan con los filtros actuales.",
    noTasksForTeamAndPerson: "{person} (equipo {team}) no tiene tareas que coincidan con los filtros.",
    noTasksForSearch: "Ninguna tarea coincide con la búsqueda \"{q}\".",
    noTasksForTeamAndSearch: "Ninguna tarea del equipo {team} coincide con la búsqueda \"{q}\".",
    noTasksForPersonAndSearch: "Ninguna tarea de {person} coincide con la búsqueda \"{q}\".",
    noTasksForTeamPersonAndSearch: "{person} (equipo {team}) no tiene tareas que coincidan con \"{q}\".",
    clearFiltersCta: "Limpiar filtros",
    allPersons: "Todas las personas",
    allPersonsCount: "Todas las personas ({count})",
    searchPerson: "Buscar persona...",
    bugsPaginationPrev: "Anterior",
    bugsPaginationNext: "Siguiente",
    bugsPaginationPage: "Página {page} de {total}",
    bugsPaginationShowing: "Mostrando {from}–{to} de {total}",
    bugsPerPage: "Por página",
    bugsLoadingMore: "Cargando más bugs...",
    bugsLoadMoreError: "No se pudieron cargar más bugs.",
    bugsLoadMoreRetry: "Reintentar",
    openTasks: "Abiertas",
    blockedTasks: "Bloqueadas",
    completedTasks: "Completadas",
    chartActive: "Activo",
    chartDone: "Hecho",
    searchTaskPlaceholder: "Buscar tarea...",
    filterByStateAria: "Filtrar por estado",
    chipInProgress: "En progreso",
    chipPending: "Pendiente",
    chipBlocked: "Bloqueada",
    chipCompleted: "Completada",
    chipResolved: "Resuelta",
    chipClosed: "Cerrada",
    fewerTasks: "Menos tareas",
    nameAZ: "Nombre A→Z",
    nameZA: "Nombre Z→A",
    personalPriority: "Prioridad personal",
    teamLabel: "Equipo",
    activeTeamAria: "Equipo activo: {team}",
    removeTeamFilterAria: "Quitar filtro del equipo {team}",
    noTasksMatchFilters: "No hay tareas que coincidan con los filtros.",
    reorderSrOnly: "Reordenar",
    iterationColumn: "Iteración",
    changedDateColumn: "Modificado",
    closedDateColumn: "Cerrado",
    priorityColumn: "Prioridad",
    assignedToColumn: "Asignado a",
    actionsColumn: "Acciones",
    typeColumn: "Tipo",
    stateColumn: "Estado",
    handoverColumn: "Handover",
    openInAdo: "Abrir en Azure DevOps",
    openTaskInAdoAria: "Abrir tarea {id} en Azure DevOps",
    copyLink: "Copiar enlace",
    taskWord: "tarea",
    tasksWord: "tareas",
    generateHandoverSummaryBtn: "Generar resumen de handover",
    noMatchesShort: "Sin coincidencias.",
    closeBtn: "Cerrar",
    priorityHigh: "Alta",
    priorityMedium: "Media",
    priorityLow: "Baja",
    priorityNone: "Sin prioridad",
    changePriorityAria: "Cambiar prioridad personal (actual: {level})",
    prioritiesBtn: "Prioridades",
    exportToJson: "Exportar a JSON",
    importFromJson: "Importar desde JSON",
    clearPriorities: "Limpiar prioridades",
    prioritiesImported: "Prioridades importadas",
    fileDownloaded: "Fichero descargado",
    importFileError: "Error al importar el fichero",
    clearPrioritiesTitle: "¿Limpiar prioridades?",
    clearPrioritiesDesc: "Se eliminarán todas las prioridades personales guardadas en este navegador. La acción no afecta a TFS.",
    cancelBtn: "Cancelar",
    clearBtn: "Limpiar",
    prioritiesCleared: "Prioridades eliminadas",
    priorityScopeFor: "Orden guardado para {name}",
    priorityScopeAll: "Orden guardado para todos",
    taskReorderedTitle: "Tarea reordenada",
    taskReorderedDesc: "La tarea {id} ahora ocupa la posición {position} de {total} en la lista de {bucket}",
    bucketLabelAll: "todos",
    manualOrderToggle: "Orden manual",
    // Bulk edit
    bulkEditBtn: "Edición en Bloque",
    bulkMembersLabel: "Miembros ({count} seleccionados)",
    bulkMaxCapacityLabel: "Capacidad Máxima (h/sem)",
    bulkBaseCapacityLabel: "Capacidad Base (h/sem)",
    bulkExample40: "Ej. 40",
    bulkExample32: "Ej. 32",
    bulkEmptyNote: "Nota: Los campos vacíos no modificarán el valor actual del miembro.",
    bulkApplyChanges: "Aplicar Cambios",
    bulkSelectAll: "Seleccionar Todos",
    bulkDeselectAll: "Deseleccionar Todos",
    // Index page
    newTeamPlaceholder: "Nombre del equipo",
    confirmDeleteTeam: '¿Eliminar equipo "{name}" y todos sus miembros?',
    reassignedTasksTitle: "Tareas reasignadas",
    // Sidebar
    exportJsonBtn: "Exportar JSON",
    importJsonBtn: "Importar JSON",
    resetDataBtn: "Reiniciar datos",
    // TaskTypeFilter
    filterByType: "Filtrar por tipo",
    typeShort: "Tipo",
    clearShort: "Limpiar",
    // Status badges
    statusAvailable: "Disponible",
    statusVacation: "Vacaciones",
    statusSickLeave: "Baja",
    statusWorkTravel: "Viaje de trabajo",
    statusOtherProject: "Otro proyecto",
    statusParentalLeave: "Baja parental",
    topicInProgress: "En progreso",
    topicPending: "Pendiente",
    topicBlocked: "Bloqueado",
    topicCompleted: "Completado",
    // Sortable rows
    dragToReorder: "Arrastrar para reordenar",
    // Handover summary dialog (tasks)
    handoverSummaryTitle: "Resumen de handover · {name}",
    handoverSummaryDesc: "Recopila tareas en progreso, pendientes y bloqueadas junto con notas, enlaces y pasos registrados. Edita libremente antes de copiar o descargar.",
    coverPersonLabel: "Persona que cubre",
    coverPersonPlaceholder: "Nombre del / de la responsable temporal",
    expectedReturnLabel: "Vuelta prevista",
    annotationsCount: "{count} anotaciones",
    loadingNotes: "Cargando notas…",
    closeAction: "Cerrar",
    downloadMd: "Descargar .md",
    copyAction: "Copiar",
    summaryCopied: "Resumen copiado al portapapeles",
    couldNotCopy: "No se pudo copiar",
    couldNotLoadNotes: "No se pudieron cargar las anotaciones",
    handoverOfHeading: "Handover de {name}",
    generatedOn: "Generado el {date}",
    coverLine: "Cubre: {name}",
    returnLine: "Vuelta prevista: {date}",
    inProgressHeading: "En progreso",
    pendingHeading: "Pendientes",
    blockedHeading: "Bloqueadas",
    noteByAuthor: "Nota ({author})",
    linkWord: "Enlace",
    stepWord: "Paso",
    noOpenTasksItalic: "_Sin tareas abiertas, en progreso ni bloqueadas._",
    // Absence handover summary
    topicCompletedFem: "Completada",
    topicBlockedFem: "Bloqueada",
    absSickLeaveLabel: "Baja médica",
    teamInline: "Equipo: {name}",
    roleInline: "Rol: {role}",
    absenceInline: "Ausencia: {type} · {start} → {end}",
    coverInline: "Cubre: {name}",
    noResponsibleInline: "Sin responsable asignado",
    reassignedFromInline: "Reasignada de: {name}",
    notesInline: "Notas: {text}",
    registeredHandoversTitle: "Handovers registrados ({count})",
    noHandoversWarning: "> ⚠️ No hay handovers registrados para esta ausencia.",
    noTopicsItalic: "_Sin temas en progreso, pendientes ni bloqueados._",
    handoversWord: "handovers",
    topicsWord: "temas",
    handoverSummaryAbsenceDesc: "Recopila temas en progreso, pendientes y bloqueados junto con los responsables que cubren a la persona durante su ausencia. Edita libremente antes de copiar o descargar.",
    // TaskHandoverNotes
    handoverNotesHeader: "Handover · notas, enlaces y próximos pasos",
    tabNotes: "Notas",
    tabLinks: "Enlaces",
    tabSteps: "Pasos",
    loadingShort: "Cargando…",
    noNotesYet: "Sin notas todavía.",
    noLinksYet: "Sin enlaces todavía.",
    noStepsYet: "Sin pasos todavía.",
    notePlaceholder: "Contexto, decisiones, dudas…",
    stepPlaceholder: "Próximo paso accionable…",
    linkTitlePlaceholder: "Título del enlace",
    addNoteBtn: "Añadir",
    editAria: "Editar",
    deleteAria: "Borrar",
    saveAction: "Guardar",
    cancelAction: "Cancelar",
    couldNotSave: "No se pudo guardar",
    couldNotDelete: "No se pudo borrar",
    couldNotUpdate: "No se pudo actualizar",
    // TfsErrorPanel
    tfsErrCors: "Sin acceso a la red del TFS (¿VPN de ROSEN activa?)",
    tfsErrMixed: "Bloqueado por contenido mixto (HTTP en página HTTPS)",
    tfsErrUnauthorized: "Autenticación rechazada",
    tfsErrForbidden: "Permisos insuficientes",
    tfsErrNotFound: "Recurso no encontrado",
    tfsErrTimeout: "Tiempo de espera agotado",
    tfsErrHttp: "Error HTTP del servidor",
    tfsErrUnknown: "Error de conexión",
    tfsErrUrlTested: "URL probada:",
    tfsErrTechDetails: "Detalles técnicos",
    tfsHintCors1: "Conéctate a la VPN de ROSEN (o usa un equipo dentro de la red corporativa). El TFS es on-prem y no es alcanzable desde internet.",
    tfsHintCors2: "Verifícalo abriendo la URL del TFS en otra pestaña del mismo dispositivo: si no carga ahí, la VPN/red no está activa.",
    tfsHintCors3: "Si la URL del TFS sí carga en el navegador pero aquí falla, entonces sí es un CORS del TFS: pide a IT añadir Access-Control-Allow-Origin en el IIS/reverse proxy.",
    tfsHintCors4: "Si el navegador menciona 'CERT': el certificado del TFS no es de confianza para tu navegador.",
    tfsHintMixed1: "La app se sirve por HTTPS, pero la URL del TFS empieza por HTTP. Los navegadores bloquean siempre esta combinación.",
    tfsHintMixed2: "Solución: pon el TFS detrás de HTTPS (recomendado) o accede a la app por HTTP (no aplicable en producción).",
    tfsHintUnauth1: "Genera un nuevo PAT en TFS → Perfil → Personal Access Tokens.",
    tfsHintUnauth2: "Comprueba que no esté caducado y que pertenece al mismo dominio que el TFS.",
    tfsHintUnauth3: "Algunas instalaciones antiguas de TFS no aceptan PAT y requieren credenciales NTLM.",
    tfsHintForb1: "El PAT necesita los scopes: Work Items (Read), Project & Team (Read), Work (Read).",
    tfsHintForb2: "Confirma que tu usuario tiene acceso al proyecto desde la web del TFS.",
    tfsHintNotFound1: "Verifica que la URL del servidor incluye /tfs si tu instalación lo usa (ej. https://tfs.empresa.net/tfs).",
    tfsHintNotFound2: "Comprueba el nombre exacto de la colección y el proyecto (sensible a mayúsculas).",
    tfsHintNotFound3: "Abre la URL completa en el navegador para descartar typos.",
    tfsHintTimeout1: "¿Estás conectado a la VPN? Si no, no puedes alcanzar el TFS interno.",
    tfsHintTimeout2: "Un firewall corporativo puede estar bloqueando peticiones desde el navegador.",
    tfsHintTimeout3: "Comprueba que el servidor TFS está operativo abriendo la URL directamente.",
    tfsHintHttp1: "El servidor respondió con un código inesperado. Revisa los logs del TFS.",
    tfsHintHttp2: "Verifica que la versión de API (5.0) es compatible con tu instalación de TFS.",
    // TfsAutocompleteInput
    tfsAutoSuggestions: "Sugerencias",
    tfsAutoFillPrereq: "Completa los campos previos y el PAT para ver sugerencias.",
    tfsAutoQuerying: "Consultando al servidor TFS…",
    tfsAutoCanType: "Puedes seguir escribiendo el valor manualmente.",
    tfsAutoNoServerResults: "Sin resultados desde el servidor.",
    tfsAutoNoMatch: "Ningún elemento coincide con lo escrito.",
    tfsAutoShowSuggestions: "Mostrar sugerencias",
    tfsAutoReload: "Recargar sugerencias",
    tfsAutoLoadError: "No se pudo cargar la lista.",
    // TfsImportDialog
    tfsImportQuerying: "Consultando Azure DevOps...",
    tfsImportSelectAllAvailable: "Seleccionar todos los disponibles ({count})",
    // AppContext toasts
    teamCreatedToast: 'Equipo "{name}" creado',
    teamDeletedToast: 'Equipo "{name}" eliminado',
    invalidHandover: "Handover inválido",
    invalidSchema: "Esquema inválido: {msg}",
    importRejectedHandovers: "Importación rechazada: hay handovers sin tema o con temas desconocidos.",
    dataImportedOk: "Datos importados correctamente",
    importPreviewTitle: "Vista previa de importación",
    importPreviewDescOk: "Se sobrescribirán los datos actuales con lo siguiente:",
    importPreviewDescError: "El archivo no se puede importar. Corrige los siguientes campos y vuelve a intentarlo:",
    importPreviewNoRecords: "El archivo es válido pero no contiene ningún registro para importar.",
    importPreviewCountTeams: "Equipos",
    importPreviewCountMembers: "Miembros",
    importPreviewCountTopics: "Temas de trabajo",
    importPreviewCountAbsences: "Ausencias",
    importPreviewCountHandovers: "Handovers",
    importPreviewConfirm: "Importar y sobrescribir",
    importPreviewCancel: "Cancelar",

    // Pat diagnostics
    patAdvancedTitle: "Diagnóstico avanzado del PAT — {ok}/{total} permisos verificados",
    patAllOk: "El PAT tiene todos los permisos necesarios.",
    patReviewRed: "Revisa los permisos marcados en rojo. Cada fila muestra el endpoint exacto y el código HTTP devuelto.",
    patMissingScopes: "Scopes que faltan en el PAT:",
    patRegenerateHint: "Regenera el PAT en TFS → Perfil → Personal Access Tokens, marcando los scopes anteriores.",
    patServerResponse: "Respuesta del servidor",
    patNetworkLabel: "Red",
    // Multi select
    multiSelectSearch: "Buscar…",
    multiSelectReload: "Recargar",
    multiSelectLoading: "Cargando…",
    multiSelectSelectedSuffixSingular: "seleccionado",
    multiSelectSelectedSuffixPlural: "seleccionados",
    multiSelectRemoveAria: "Quitar {item}",
    multiSelectUnknownError: "Error desconocido",
    // CORS guide
    copiedToClipboard: "Copiado al portapapeles",
    copyAria: "Copiar",
    corsViewGuide: "Ver guía rápida de configuración",
    corsDialogTitle: "Configurar CORS en el TFS",
    corsDialogDesc: "El TFS debe responder con cabeceras CORS que permitan el origen <ORIGIN>. Pide a tu equipo de IT que aplique uno de estos snippets en el reverse proxy o IIS que sirve el TFS.",
    corsIisExplain: "TFS suele desplegarse sobre IIS. Edita el web.config del sitio y añade el bloque siguiente. Reinicia el sitio en IIS Manager tras guardar.",
    corsIisWarn: "⚠️ Si IIS también responde a las peticiones OPTIONS (preflight), asegúrate de que el handler OPTIONSVerbHandler esté habilitado y devuelva 200/204.",
    corsNginxExplain: "Si delante del TFS hay un nginx (reverse proxy), añade este bloque en el server que sirve el host del TFS y recarga con nginx -s reload.",
    corsApacheExplain: "Para Apache httpd como reverse proxy, asegúrate de tener mod_headers y mod_rewrite habilitados, y reinicia el servicio tras guardar.",
    corsCheckIntro: "abre DevTools → Network,",
    corsCheckTail: "con la cabecera",
    corsSecurityLabel: "Seguridad:",
    corsSecurityBody: "usa siempre un origen específico (no *) cuando envíes credenciales.",
    // BugsPage filter
    bugsRemoveIterationFilter: "Quitar filtro",
    bugsFilterByIteration: "Filtrar por esta iteración",
    bugsClearFiltersTitle: "Limpiar filtros",
    bugsSearchPlaceholder: "Buscar por título o ID...",
    // AzureDevOps settings
    adoFixFieldsDiagnostics: "Corrige los campos marcados antes de ejecutar el diagnóstico.",
    adoAllPermsOk: "✅ Todos los permisos del PAT verificados",
    adoMissingScopes: "Faltan scopes: {scopes}",
    adoSomeChecksFailed: "Algunas comprobaciones fallaron — revisa el panel",
    adoDiagnosticsErr: "Error en diagnóstico",
    adoFixFieldsConnection: "Corrige los campos marcados antes de probar la conexión.",
    adoDisabledReasonProjects: "Introduce servidor, colección y PAT para listar proyectos.",
    adoDisabledReasonTeams: "Introduce servidor, colección, proyecto y PAT para listar equipos.",
    adoAdvancedPatCheck: "Comprobación avanzada del PAT",
    adoLastDiagnostic: "Último diagnóstico: {date}",
    adoRodatScopeTitle: "Alcance del equipo RODAT",
    adoRodatScopeDesc: "Selecciona las áreas e iteraciones de Azure DevOps que se usarán al cargar Features y Tareas. Si no eliges nada, se usan los valores por defecto",
    adoAreasLabel: "Áreas (Features y Tareas)",
    adoSelectAreasPh: "Selecciona una o varias áreas…",
    adoNoAreasFoundEmpty: "No se encontraron áreas para este proyecto.",
    adoDisabledReasonAreas: "Configura servidor, colección, proyecto y PAT para cargar las áreas.",
    adoAreasFilterHint: "Las features y tareas se filtrarán a estas áreas (incluye descendientes).",
    adoIterationsLabel: "Iteraciones (solo Tareas)",
    adoSelectIterationsPh: "Selecciona una o varias iteraciones…",
    adoNoIterationsFound: "No se encontraron iteraciones para este proyecto.",
    adoDisabledReasonIterations: "Configura servidor, colección, proyecto y PAT para cargar las iteraciones.",
    adoIterationsFilterHint: "Las tareas se filtrarán a estas iteraciones (incluye descendientes).",
    adoBugsQueryLabel: "Query de Bugs (ID o ruta)",
    adoBugsQueryPlaceholder: "p. ej. 12345678-1234-1234-1234-123456789012 o Shared Queries/Equipo/Bugs",
    adoBugsQueryHint: "ID (GUID) o ruta de una query existente en Azure DevOps que devuelve los bugs a mostrar en la página Bugs.",
    adoAutosaved: "Cambios guardados automáticamente · {time}",
    // Features state labels
    stateActive: "Activo",
    stateDone: "Completado",
    tasksSectionHeading: "Tareas",
    couldNotReadTeamAreas: "No se pudieron leer las áreas del equipo: {error}",
    // Team pulse dashboard
    noAssociatedTasks: "Sin tareas asociadas",
    plusMoreSuffix: "+{count} más",
    // Epics
    epics: "Epics",
    epicsPageTitle: "Epics",
    epicsPageDescription: "Epics obtenidos desde Azure DevOps y filtrados por tags configurados.",
    epicsTabRoadmap: "Delivery plan",
    epicsTabList: "Lista",
    epicsEmptyNoSettings: "Aún no has configurado la conexión con Azure DevOps.",
    epicsEmptyNoTags: "Configura al menos un tag en los ajustes de Azure DevOps para listar los Epics.",
    epicsNoResults: "No hay Epics que coincidan con los filtros actuales.",
    epicsLoading: "Cargando Epics desde Azure DevOps...",
    epicsRefresh: "Refrescar",
    epicsCount: "epics",
    epicsColId: "ID",
    epicsColTitle: "Título",
    epicsColState: "Estado",
    epicsColAssignee: "Asignado a",
    epicsColTags: "Tags",
    epicsColArea: "Área",
    epicsColTargetDate: "Target date",
    epicsColChangedDate: "Modificado",
    epicsFilterSearch: "Buscar por título, ID o persona...",
    epicsFilterState: "Estado",
    epicsFilterTag: "Tag",
    epicsFilterTags: "Tags",
    epicsFilterTagsPlaceholder: "Todos los tags",
    epicsFilterTagsSelected: "seleccionados",
    epicsFilterClear: "Limpiar",
    epicsFilterAll: "Todos",
    epicsNoDateBucket: "Sin fecha",
    epicsUnassigned: "Sin asignar",
    epicsOpenSettings: "Abrir ajustes",
    epicsTagsConfiguredLabel: "Tags configurados",
    epicsEffectiveProjectLabel: "Proyecto consultado",
    epicsEffectiveProjectMain: "Proyecto principal",
    epicsEffectiveProjectOverride: "Proyecto de Epics",
    epicsQuarterEpicsSuffix: "epics",
    epicsTabTimeline: "Timeline",
    epicsTabHeatmap: "Heatmap",
    epicsTimelineTodayLabel: "Hoy",
    epicsTimelineGroupBy: "Agrupar por",
    epicsTimelineNoDatesHint: "Sin fechas",
    epicsTimelineRange4: "4 trimestres",
    epicsTimelineRange6: "6 trimestres",
    epicsTimelineRange8: "8 trimestres",
    epicsGroupNone: "Sin agrupar",
    epicsGroupArea: "Área",
    epicsGroupAssignee: "Persona",
    epicsHeatmapRowBy: "Filas por",
    epicsHeatmapNoDateColumn: "Sin fecha",
    epicsHeatmapTotal: "Total",
    epicsHeatmapCellDialogTitle: "Epics en la celda",
    // Settings — Epics section
    adoEpicsSectionTitle: "Epics",
    adoEpicsSectionDesc: "Configura el origen y los tags para la vista Epics.",
    adoEpicsQueryIdLabel: "Query de Epics (ID o ruta)",
    adoEpicsQueryIdPlaceholder: "GUID o Shared Queries/Equipo/Epics (opcional)",
    adoEpicsQueryIdHint: "Opcional. Si se deja vacío, se listan todos los Epics del proyecto (opcionalmente restringidos por las áreas configuradas).",
    adoEpicsTagsLabel: "Tags permitidos",
    adoEpicsTagsPlaceholder: "Escribe un tag y pulsa Enter",
    adoEpicsTagsHint: "Solo se mostrarán los Epics que contengan alguno de estos tags.",
    adoEpicsProjectLabel: "Proyecto de Epics (opcional)",
    adoEpicsProjectPlaceholder: "p. ej. Software",
    adoEpicsProjectHint: "Si los Epics están en otro proyecto de la misma colección (por ejemplo 'Software' en vez de 'SDES'), indícalo aquí. Si se deja vacío se usa el proyecto principal.",
    adoEpicsProjectSameAsMain: "Igual que el proyecto principal",
    epicsEffectiveTeamLabel: "Equipo",
    adoEpicsScopeTitle: "Alcance de Epics (equipo Software)",
    adoEpicsScopeDesc: "Configura un equipo, áreas e iteraciones específicos para la vista Epics. Si se dejan vacíos, se usan los del alcance principal.",
    adoEpicsTeamLabel: "Equipo de Epics (opcional)",
    adoEpicsTeamPlaceholder: "p. ej. Software Team",
    adoEpicsTeamHint: "Equipo dentro del proyecto de Epics. Se usa como contexto al resolver los queries guardados.",
    adoEpicsAreaPathsLabel: "Áreas de Epics (opcional)",
    adoEpicsIterationPathsLabel: "Iteraciones de Epics (opcional)",
    adoEpicsScopeHint: "Estos valores solo se aplican en la vista Epics.",
    adoEpicsScopeTestButton: "Probar alcance de Epics",
    adoEpicsScopeTestOk: "Alcance de Epics validado",
    adoEpicsScopeTestPartial: "Conexión OK, pero faltan valores en el alcance",
    adoEpicsScopeTestTeamsFound: "Equipos encontrados",
    adoEpicsScopeTestAreasFound: "Áreas disponibles",
    adoEpicsScopeTestIterationsFound: "Iteraciones disponibles",
    adoEpicsScopeTestTeamMissing: "El equipo indicado no existe en el proyecto",
    adoEpicsScopeTestAreasMissing: "Áreas configuradas que no existen",
    adoEpicsScopeTestIterationsMissing: "Iteraciones configuradas que no existen",
    epicDetailCreatedBy: "Creado por",
    epicDetailCreated: "Creado",
    epicDetailStartDate: "Start date",
    epicDetailIteration: "Iteración",
    epicDetailDescription: "Descripción",
    epicDetailNoDescription: "Sin descripción.",
    epicDetailLinks: "Enlaces y relaciones",
    epicDetailNoLinks: "Sin enlaces.",
    epicDetailHistory: "Historial de cambios",
    epicDetailNoHistory: "Sin cambios registrados.",
    epicDetailOpenInAdo: "Abrir en Azure DevOps",
  },

  en: {
    dashboard: "Dashboard",
    dashboardDesc: "General overview of your teams",
    searchPeople: "Search people...",
    members: "Members",
    absent: "Absent",
    upcoming: "Upcoming",
    activeHandovers: "Active handovers",
    noActiveHandovers: "No active handovers at this time.",
    navigation: "Navigation",
    absences: "Absences",
    handovers: "Handovers",
    bugs: "Bugs",
    bugsPageTitle: "Bugs",
    bugsPageDescription: "Bugs fetched from an existing Azure DevOps query.",
    bugsColumnId: "ID",
    bugsColumnTitle: "Title",
    bugsColumnAssignee: "Assigned to",
    bugsColumnState: "State",
    bugsColumnIteration: "Iteration",
    bugsColumnArea: "Area",
    bugsColumnSeverity: "Severity",
    bugsFilterSearch: "Search by title, ID or person...",
    bugsFilterAssignee: "Assignee",
    bugsFilterState: "State",
    bugsFilterSeverity: "Severity",
    bugsFilterIteration: "Iteration",
    bugsFilterAll: "All",
    bugsRefresh: "Refresh",
    bugsCount: "bugs",
    bugsEmpty: "The query returned no bugs.",
    bugsLoading: "Loading bugs from Azure DevOps...",
    bugsNoConnection: "You haven't configured the Azure DevOps connection yet.",
    bugsNoIterationConfigured: "Configure at least one iteration in the Azure DevOps settings to list bugs.",
    bugsIterationPathsLabel: "Configured iterations",
    bugsIterationPathsNone: "No iterations configured",
    bugsOpenSettings: "Open settings",
    bugsUnassigned: "Unassigned",
    bugDetailPriority: "Priority",
    bugDetailCreatedBy: "Created by",
    bugDetailCreated: "Created",
    bugDetailChanged: "Changed",
    bugDetailTags: "Tags",
    bugDetailDescription: "Description",
    bugDetailNoDescription: "No description.",
    bugDetailReproSteps: "Repro steps",
    bugDetailLinks: "Links and relations",
    bugDetailNoLinks: "No links.",
    bugDetailOpenInAdo: "Open in Azure DevOps",
    features: "Features",
    tasks: "Tasks",
    workload: "Workload & Capacity",
    pulse: "Pulse",
    featuresAndTasks: "Features & Tasks",
    team: "Team",
    // Team page
    teamNotFound: "Team not found",
    add: "Add",
    newMember: "New member",
    name: "Name",
    role: "Role",
    search: "Search...",
    all: "All",
    allTeams: "All teams",
    allTypes: "All types",
    available: "Available",
    vacation: "Vacation",
    sickLeave: "Sick leave",
    workTravel: "Work travel",
    otherProject: "Other project",
    parentalLeave: "Parental leave",
    workTopics: "Work topics",
    addTopic: "Add topic",
    topicName: "Topic name...",
    description: "Description",
    descPlaceholder: "Description...",
    status: "Status",
    pending: "Pending",
    inProgress: "In progress",
    blocked: "Blocked",
    completed: "Completed",
    save: "Save",
    create: "Create",
    noTopics: "No assigned topics",
    deleteMember: "Delete member",
    errSelectMember: "Select at least one member",
    errInvalidMaxCapacity: "Invalid max capacity",
    errInvalidBaseCapacity: "Invalid base capacity",
    errBaseGtMax: "Base capacity cannot be greater than max capacity",
    errBulkConflict: "For some members, the new configuration causes base capacity to exceed max capacity. Please review the values.",
    capacityUpdated: "Capacity updated for {count} members",
    errNameMinLength: "Name must be at least 2 characters",
    errRoleMinLength: "Role must be at least 2 characters",
    errMaxLtBase: "Max capacity cannot be less than base capacity",
    errBaseGtMaxSingle: "Base capacity cannot be greater than max capacity",
    resetCapacityConfirmTitle: "Reset capacity?",
    resetCapacityConfirmDesc: "Are you sure you want to reset {name}'s capacity to default values (Max: 40h, Base: 32h)?",
    resetCapacity: "Reset",
    undo: "Undo",
    capacityResetSuccess: "Capacity reset successfully",
    capacityConfig: "Capacity Configuration",
    maxCapacity: "Max Capacity (h/week)",
    baseCapacity: "Base Capacity (h/week)",
    // Absences page
    absencesDesc: "Vacation and leave management",
    exportCsv: "Export CSV",
    newAbsence: "New absence",
    editAbsence: "Edit absence",
    updateAbsence: "Update absence",
    registerAbsence: "Register absence",
    person: "Person",
    select: "Select...",
    type: "Type",
    start: "Start",
    end: "End",
    date: "Date",
    register: "Register",
    timeline: "Timeline",
    list: "List",
    noAbsencesMonth: "No absences this month",
    noAbsences: "No absences registered.",
    totalDays: "total days",
    days: "days",
    // Handovers page
    handoversDesc: "Work handover management",
    filterByDate: "Filter by date",
    from: "From",
    to: "To",
    clearFilter: "Clear filter",
    createHandover: "Create handover",
    newHandover: "New handover",
    absentPerson: "Absent person",
    covers: "Covers",
    topicsToTransfer: "Topics to transfer",
    notes: "Notes",
    notesPlaceholder: "Instructions for the handover...",
    noHandovers: "No handovers created.",
    editHandover: "Edit handover",
    updateHandover: "Update handover",
    created: "Created",
    handoverDetail: "Handover detail",
    absenceType: "Type",
    absencePeriod: "Absence period",
    topicCount: "topics",
    deleteHandoverTitle: "Delete handover?",
    deleteHandoverDesc: "This action cannot be undone. The handover will be permanently deleted.",
    deleteAbsenceTitle: "Delete absence?",
    deleteAbsenceDesc: "This action cannot be undone. The absence will be permanently deleted.",
    handoverSelectAbsent: "Select the absent person",
    handoverSelectCover: "Select who covers",
    handoverSelectTopics: "Select at least one topic",
    noTopicsAvailable: "This person has no assigned topics. You can continue without selecting any.",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmMove: "Move member?",
    confirmMoveDesc: "Move {name} to {team}?",
    confirmDelete: "Delete",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Team capacity",
    analyticsHandoverRate: "Handover rate",
    analyticsActiveAbsences: "Active absences",
    analyticsActive: "active",
    analyticsCurrently: "currently",
    analyticsTeamCapacity: "Capacity by team",
    analyticsAbsenceType: "Absence type",
    analyticsAbsenceTrend: "Absence trend (21 days)",
    analyticsNoData: "No data available",
    analyticsNoAbsences: "No active absences",
    // Notifications
    notifTitle: "Notifications",
    notifCritical: "critical",
    notifWarnings: "warnings",
    notifEmpty: "All clear, no alerts",
    notifNoHandover: "Absence without handover",
    notifNoHandoverDesc: "{name} is absent with no handover assigned",
    notifUpcomingNoHandover: "Upcoming absence without handover",
    notifUpcomingNoHandoverDesc: "{name} will be absent on {date} with no handover",
    notifCoverageGap: "Coverage gap",
    notifCoverageGapDesc: "{team}: {absent} of {total} members absent",
    notifUncoveredTopics: "Uncovered topics",
    notifUncoveredTopicsDesc: "{count} topics from {name} uncovered during absence",
    // Import absences
    importAbsences: "Import absences",
    importDropzone: "Drag a file or click to select",
    importFormats: "CSV, XLSX or XLS",
    importRows: "rows detected",
    importChangeFile: "Change file",
    importSelectColumn: "Select column",
    importPreviewSample: "Preview of first rows:",
    importValidate: "Validate data",
    importValid: "valid",
    importInvalid: "with errors",
    importBackToMapping: "Back to mapping",
    importConfirm: "Import absences",
    importSuccess: "absences imported",
    importParseError: "Error reading file",
    importEmpty: "File is empty",
    importUnsupportedFormat: "Unsupported format. Use CSV or XLSX",
    importErrNoName: "No name",
    importErrMemberNotFound: "Member not found",
    importErrInvalidType: "Invalid type",
    importErrInvalidStart: "Invalid start date",
    importErrInvalidEnd: "Invalid end date",
    importErrDateOrder: "Start after end",
    // Invent format
    importModeGeneric: "Generic (CSV / Excel)",
    importModeInvent: "Invent format",
    importInventDropzone: "Drag the Absent.xlsx file exported from Invent",
    importInventFormats: "Only .xlsx",
    importAutoDetectedInvent: "ROSEN format detected — switched to Invent parser",
    importInventSummary: "{imported} absences ready · {unmatched} unmatched · {skipped} rows skipped",
    importInventNoLogin: "Login not found",
    importInventLoginCol: "Login",
    importInventMemberCol: "Member",
    importResultTitle: "Last import",
    importResultCreated: "absences created",
    importResultSkipped: "rows skipped",
    importResultUnmatched: "unmatched logins",
    importResultDismiss: "Dismiss summary",
    importValidationFailed: "The file does not match the expected format",
    importValidationHint: "Expected headers: A=Work date, C=Person, D=Duration, E=Activity kind. Dates as YYYY-MM-DD, DD/MM/YYYY or Excel date cell.",
    importUnmatchedRangesLabel: "pending ranges",
    importAssignToMember: "Assign to member…",
    // JSON import (backup)
    importModeJson: "JSON (backup)",
    importJsonDropzone: "Drop the exported JSON file",
    importJsonFormats: "Only .json — only absences will be imported",
    importJsonNoAbsences: "The file contains no absences",
    importJsonMemberNotFound: "Member not found",
    importJsonDuplicate: "Duplicate",
    importJsonStatusOk: "OK",
    importJsonSummary: "{ok} new · {dup} duplicates · {missing} unmatched",
    loginName: "Login name",
    loginNamePlaceholder: "e.g. jsmith",
    // Azure DevOps / TFS
    importTfsTeamMembers: "Import from ADO",
    importTfsTeamMembersTitle: "Import members from Azure DevOps",
    importTfsTeamMembersDesc: "Select who you want to add to this Lovable team.",
    importTfsConfigureAlert: "To import, you must first configure the connection and select a team in Azure DevOps Settings.",
    importTfsNoMembers: "No members were found in the ADO team, or the list could not be loaded.",
    importTfsDuplicateTooltip: "Already exists in the current team",
    importTfsImportCount: "Add {count} member(s)",
    importTfsSuccess: "{count} member(s) added successfully",
    importTfsConfigureTitle: "Incomplete configuration",
    importTfsConfigureHint1: "Go to Settings › Azure DevOps and fill in server, collection, project, PAT and team.",
    importTfsErrCorsTitle: "No access to TFS (is the ROSEN VPN on?)",
    importTfsErrCorsHint1: "Connect to the ROSEN VPN or use a machine on the corporate network before importing. The on-prem TFS is not reachable from the public internet.",
    importTfsErrCorsHint2: "If you are already on the network, try opening the TFS URL in another tab; if it loads there, it's a TFS CORS issue (ask IT).",
    importTfsErrMixedTitle: "Mixed content blocked",
    importTfsErrMixedHint1: "This app uses HTTPS but the configured TFS server uses HTTP. Use an https:// URL in settings.",
    importTfsErrTimeoutTitle: "Request timed out",
    importTfsErrTimeoutHint1: "The TFS server didn't respond in time. Check the VPN / internal network and that the server URL is reachable.",
    importTfsErrTimeoutHint2: "Run a connection test from Settings › Azure DevOps to confirm connectivity.",
    importTfsErrUnauthorizedTitle: "PAT invalid or expired (401)",
    importTfsErrUnauthorizedHint1: "Regenerate the Personal Access Token in Azure DevOps and save it again in Settings.",
    importTfsErrUnauthorizedHint2: "Make sure the PAT hasn't expired or been revoked.",
    importTfsErrForbiddenTitle: "Insufficient permissions (403)",
    importTfsErrForbiddenHint1: "The PAT needs the scopes: Project & Team (Read), Work Items (Read).",
    importTfsErrForbiddenHint2: "Check that your user has access to the selected team.",
    importTfsErrNotFoundTitle: "Team or project not found (404)",
    importTfsErrNotFoundHint1: "Check that collection, project and team in Settings match exactly those in TFS.",
    importTfsErrNotFoundHint2: "If the team was renamed, re-select it in Settings › Azure DevOps.",
    importTfsErrHttpTitle: "HTTP error {status}",
    importTfsErrHttpHint1: "The TFS server returned an error. Retry or review the configuration.",
    importTfsErrUnknownTitle: "Import failed",
    importTfsErrUnknownHint1: "Retry. If it persists, run a connection test from Settings › Azure DevOps.",
    importTfsErrShowDetail: "Show technical details",
    importTfsHistoryTitle: "Import history",
    importTfsHistoryCount: "{count} entries",
    importTfsHistoryAdded: "{count} member(s) added",
    importTfsHistoryReview: "Review",
    importTfsHistoryReviewTitle: "Past import",
    importTfsHistoryEmpty: "No members were recorded for this import.",
    importTfsRoleLabel: "Role assigned to imported members",
    importTfsRoleCustom: "Custom…",
    importTfsRolePlaceholder: "Type a role…",
    importTfsRoleRequired: "Pick a role before importing",
    adoTitle: "Azure DevOps / TFS",
    adoDesc: "Connect to Azure DevOps Server (on-premise TFS) or Azure DevOps cloud",
    adoConnection: "Connection",
    adoConnectionDesc: "Enter your TFS server details and a PAT with read permissions",
    adoServerUrl: "Server URL",
    adoServerUrlHint: "E.g. https://tfs.company.net/tfs (without the collection)",
    adoCollection: "Collection",
    adoCollectionHint: "Project collection name in TFS (e.g. RNDCollection)",
    adoOrganization: "Organization (cloud)",
    adoOrgHint: "Only for Azure DevOps cloud (dev.azure.com/{org}). Leave empty for on-premise TFS.",
    adoProject: "Project",
    adoTeam: "Team (optional)",
    adoTeamHint: "Filter by team inside the project, if applicable",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Requires permissions: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Test connection",
    adoConnectionOk: "Connection successful",
    adoConnectionFailed: "Connection failed",
    adoFillAllFields: "Fill in the required fields (URL, collection, project and PAT)",
    adoLoginRequired: "Log in to continue",
    adoTestFirst: "Test the connection first",
    adoSyncSettings: "Synchronization",
    adoAutoSync: "Auto sync",
    adoAutoSyncDesc: "Periodically sync with TFS",
    adoSyncInterval: "Interval",
    adoMinutes: "minutes",
    adoHour: "hour",
    adoLastSync: "Last sync",
    adoSaveSettings: "Save settings",
    adoUpdateSettings: "Update settings",
    adoSettingsSaved: "Settings saved",
    adoSettingsDeleted: "Settings deleted",
    adoDisconnect: "Disconnect",
    adoNetworkWarningTitle: "Requires corporate network access",
    adoNetworkWarningBody: "The connection runs directly from your browser to the TFS server. You must be on the internal network or connected via VPN, and TFS must allow CORS from this app's origin.",
    // Auth
    authLogin: "Log in",
    authSignup: "Sign up",
    authPassword: "Password",
    authSubtitle: "Handover and team management",
    authNamePlaceholder: "Your name",
    authLoginSuccess: "Logged in",
    authSignupSuccess: "Account created successfully",
    authPasswordMin: "Password must be at least 6 characters",
    authForgotPassword: "Forgot your password?",
    authResetPassword: "Reset password",
    authResetDesc: "Enter your email and we'll send you a link",
    authSendReset: "Send link",
    authResetSent: "Link sent, check your inbox",
    authBackToLogin: "Back to login",
    authNewPassword: "New password",
    authNewPasswordDesc: "Enter your new password",
    authUpdatePassword: "Update password",
    authPasswordUpdated: "Password updated successfully",
    authInvalidResetLink: "Invalid or expired reset link",
    authLogout: "Log out",
    bulkCapacityEditTitle: "Bulk Capacity Edit",
    preloadingAreas: "Preloading areas...",
    usingCache: "Using cache",
    statusDistribution: "Status distribution",
    statusDistributionDesc: "What is currently running",
    topTasks: "Top {count} with most tasks",
    cache: "Cache",
    moreTasks: "More tasks",
    lessTasks: "Fewer tasks",
    defaultSort: "Default",
    sortBy: "Sort by",
    title: "Title",
    noArea: "(no area)",
    noIteration: "(no iteration)",
    noTitle: "(no title)",
    outOfScopeHidden: "Out-of-scope items automatically hidden",
    errTeamAreasUpdate: "Failed to update team areas list. Using latest cached version.",
    errPeopleUpdate: "Failed to update people list. Showing latest cached list.",
    errIncompleteAdoConfig: "Incomplete Azure DevOps configuration. Showing local data.",
    hideHandover: "Hide handover",
    addHandover: "Add handover",
    tasksSubtitle: "Assigned work per person, open and in progress.",
    featuresSubtitle: "Project initiatives and their overall progress.",
    generalOverview: "General overview of the project's ongoing work.",
    workloadSubtitle: "Availability and workload grouped by week (only In Progress tasks).",
    workloadSubtitleAll: "Availability and workload grouped by week (all active tasks).",
    taskDetailInProgress: "Task Details (In Progress) - {name}",
    taskDetailAll: "Task Details (All) - {name}",
    inProgressTasksCount: "{count} In Progress",
    allTasksCount: "{count} Tasks",
    onlyInProgress: "Only In Progress",
    allTasks: "All tasks",
    addTeam: "Add team",
    ongoing: "Ongoing",
    upcomingStatus: "Upcoming",
    checkHowTo: "How to check:",
    checkCorsDetails: "click Test connection and check that the OPTIONS (preflight) request receives",
    adoAreas: "Areas (Features and Tasks)",
    errFieldsDiagnostics: "Fix the marked fields before running diagnostics.",
    errDiagnostics: "Diagnostics error",
    errFieldsConnection: "Fix the marked fields before testing the connection.",
    errAdoProjects: "Enter server, collection, and PAT to list projects.",
    errAdoTeams: "Enter server, collection, project, and PAT to list teams.",
    adoSelectAreas: "Select one or more areas...",
    adoNoAreasFound: "No areas found for this project.",
    errAdoLoadAreas: "Configure server, collection, project, and PAT to load areas.",
    errAdoLoadIterations: "Configure server, collection, project, and PAT to load iterations.",
    errImportInvalidJson: "Import error: invalid JSON file",
    confirmImportOverwrite: "Are you sure? This will overwrite all current data with the selected file's data.",
    writeSomething: "Write something",
    max2000Chars: "Maximum 2000 characters",
    invalidUrl: "Invalid URL",
    urlTooLong: "URL too long",
    mustBeLoggedIn: "You must be logged in",
    anonymous: "Anonymous",
    noteAdded: "Note added",
    noMatchingItems: "No matching items found.",
    // Not found
    pageNotFound: "Oops! Page not found",
    returnHome: "Return to Home",
    workloadAndCapacity: "Workload and Availability",
    allMembers: "All members",
    selectedCount: "{count} selected",
    searchMember: "Search member...",
    noResults: "No results.",
    weeks: "Weeks",
    nWeeks: "{count} Weeks",
    member: "Member",
    weekDate: "Week {date}",
    effortHours: "Effort: {hours}h",
    noTasksThisWeek: "No tasks assigned for this week.",
    filtersApplied: "Filters applied to Features and Tasks queries. Change them in Settings › Azure DevOps.",
    iterationsTasks: "Iterations (Tasks)",
    featureCount: "{count} feature",
    featuresCount: "{count} features",
    taskCount: "{count} task",
    tasksCountPlural: "{count} tasks",
    featuresOutOfArea: "Features out of area ({count})",
    tasksOutOfArea: "Tasks out of area ({count})",
    tasksOutOfIteration: "Tasks out of iteration ({count})",
    projectFeatures: "Project features",
    featureProgress: "Progress per feature with associated tasks",
    noFeaturesToShow: "No features to show.",
    tasksRatio: "{done} / {total} tasks",
    loadPerPerson: "Load per person",
    tasksPerPerson: "Tasks per person",
    fetchAreasError: "Could not read team areas: {error}",
    unassigned: "Unassigned",
    effectiveScope: "Effective scope",
    resultWithScope: "Result with this scope",
    noCustomScope: "No custom scope in Settings; using RODAT team defaults.",
    showingXofYFeatures: "Showing {x} of {y} features",
    showingXofYTasks: "Showing {x} of {y} tasks",
    excludedOutOfAreaFeatures: "Excluded: {count} out-of-area features,",
    excludedOutOfAreaTasks: " {count} out-of-area tasks,",
    excludedOutOfIterTasks: " {count} out-of-iteration tasks.",
    viewHiddenAudit: "View hidden items audit",
    area: "Area",
    iterationTasks: "Iteration (tasks)",
    expectedUnder: "Expected under {paths}",
    copyLinkTask: "Copy link for task {id}",
    copyLinkFeature: "Copy link for feature {id}",
    linkCopied: "Link for {type} #{id} copied",
    linkCopyFailed: "Failed to copy link",
    workDistribution: "Work distribution per person — only open and in-progress.",
    personCount: "{count} person",
    personsCount: "{count} persons",
    filtering: "filtering",
    inProgressPlural: "in progress",
    pendingPlural: "pending",
    wipBadgeLabel: "WIP",
    wipBadgeTooltip: "{n} tasks/bugs in progress or pending",
    tasksViewFilterHint: "Showing open / in progress tasks and bugs closed in the last 10 days.",
    wipDetailsTitle: "Current load · {person}",
    wipDetailsDescription: "{n} tasks and bugs counted in WIP.",
    wipDetailsEmpty: "No items in progress.",
    wipTooltipFormulaAll: "Counts tasks and bugs in Open or In Progress state.",
    wipTooltipFormulaTasks: "Counts Open / In Progress tasks and bugs, plus bugs closed in the last 10 days.",
    wipTooltipClickHint: "Click to see the breakdown.",
    wipBreakdownActiveTasks: "Tasks in progress",
    wipBreakdownActiveBugs: "Bugs in progress",
    wipBreakdownPendingTasks: "Pending tasks",
    wipBreakdownPendingBugs: "Pending bugs",
    wipBreakdownRecentClosedBugs: "Closed bugs (10 d)",
    blockedPlural: "blocked",
    completedPlural: "completed",
    resolvedPlural: "resolved",
    closedPlural: "closed",
    confirmChangesBeforeApply: "Confirm changes before applying",
    unappliedChanges: "Unapplied changes",
    discard: "Discard",
    apply: "Apply",
    viewByPerson: "View by person",
    viewFlatList: "View flat list",
    showingMaxOf: "Showing {max} of {total} tasks — refine filters to see more.",
    noPersonsMatching: "No persons with tasks matching current filters.",
    noTasksForTeam: "No tasks assigned to members of {team} team.",
    noTasksForPerson: "{person} has no tasks matching current filters.",
    noTasksForTeamAndPerson: "{person} ({team} team) has no tasks matching current filters.",
    noTasksForSearch: "No tasks match the search \"{q}\".",
    noTasksForTeamAndSearch: "No tasks in {team} team match the search \"{q}\".",
    noTasksForPersonAndSearch: "No tasks for {person} match the search \"{q}\".",
    noTasksForTeamPersonAndSearch: "{person} ({team} team) has no tasks matching \"{q}\".",
    clearFiltersCta: "Clear filters",
    allPersons: "All persons",
    allPersonsCount: "All persons ({count})",
    searchPerson: "Search person...",
    bugsPaginationPrev: "Previous",
    bugsPaginationNext: "Next",
    bugsPaginationPage: "Page {page} of {total}",
    bugsPaginationShowing: "Showing {from}–{to} of {total}",
    bugsPerPage: "Per page",
    bugsLoadingMore: "Loading more bugs...",
    bugsLoadMoreError: "Could not load more bugs.",
    bugsLoadMoreRetry: "Retry",
    openTasks: "Open",
    blockedTasks: "Blocked",
    completedTasks: "Completed",
    chartActive: "Active",
    chartDone: "Done",
    searchTaskPlaceholder: "Search task...",
    filterByStateAria: "Filter by state",
    chipInProgress: "In progress",
    chipPending: "Pending",
    chipBlocked: "Blocked",
    chipCompleted: "Completed",
    chipResolved: "Resolved",
    chipClosed: "Closed",
    fewerTasks: "Fewer tasks",
    nameAZ: "Name A→Z",
    nameZA: "Name Z→A",
    personalPriority: "Personal priority",
    teamLabel: "Team",
    activeTeamAria: "Active team: {team}",
    removeTeamFilterAria: "Remove filter for team {team}",
    noTasksMatchFilters: "No tasks match the filters.",
    reorderSrOnly: "Reorder",
    iterationColumn: "Iteration",
    changedDateColumn: "Changed",
    closedDateColumn: "Closed",
    priorityColumn: "Priority",
    assignedToColumn: "Assigned to",
    actionsColumn: "Actions",
    typeColumn: "Type",
    stateColumn: "State",
    handoverColumn: "Handover",
    openInAdo: "Open in Azure DevOps",
    openTaskInAdoAria: "Open task {id} in Azure DevOps",
    copyLink: "Copy link",
    taskWord: "task",
    tasksWord: "tasks",
    generateHandoverSummaryBtn: "Generate handover summary",
    noMatchesShort: "No matches.",
    closeBtn: "Close",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    priorityNone: "No priority",
    changePriorityAria: "Change personal priority (current: {level})",
    prioritiesBtn: "Priorities",
    exportToJson: "Export to JSON",
    importFromJson: "Import from JSON",
    clearPriorities: "Clear priorities",
    prioritiesImported: "Priorities imported",
    fileDownloaded: "File downloaded",
    importFileError: "Error importing file",
    clearPrioritiesTitle: "Clear priorities?",
    clearPrioritiesDesc: "All personal priorities stored in this browser will be removed. This action does not affect TFS.",
    cancelBtn: "Cancel",
    clearBtn: "Clear",
    prioritiesCleared: "Priorities cleared",
    priorityScopeFor: "Order saved for {name}",
    priorityScopeAll: "Order saved for everyone",
    taskReorderedTitle: "Task reordered",
    taskReorderedDesc: "Task {id} is now at position {position} of {total} in {bucket}'s list",
    bucketLabelAll: "everyone",
    manualOrderToggle: "Manual order",
    // Bulk edit
    bulkEditBtn: "Bulk edit",
    bulkMembersLabel: "Members ({count} selected)",
    bulkMaxCapacityLabel: "Max capacity (h/week)",
    bulkBaseCapacityLabel: "Base capacity (h/week)",
    bulkExample40: "e.g. 40",
    bulkExample32: "e.g. 32",
    bulkEmptyNote: "Note: empty fields will not change the member's current value.",
    bulkApplyChanges: "Apply changes",
    bulkSelectAll: "Select all",
    bulkDeselectAll: "Deselect all",
    // Index page
    newTeamPlaceholder: "Team name",
    confirmDeleteTeam: 'Delete team "{name}" and all its members?',
    reassignedTasksTitle: "Reassigned tasks",
    // Sidebar
    exportJsonBtn: "Export JSON",
    importJsonBtn: "Import JSON",
    resetDataBtn: "Reset data",
    // TaskTypeFilter
    filterByType: "Filter by type",
    typeShort: "Type",
    clearShort: "Clear",
    // Status badges
    statusAvailable: "Available",
    statusVacation: "Vacation",
    statusSickLeave: "Sick leave",
    statusWorkTravel: "Work travel",
    statusOtherProject: "Other project",
    statusParentalLeave: "Parental leave",
    topicInProgress: "In progress",
    topicPending: "Pending",
    topicBlocked: "Blocked",
    topicCompleted: "Completed",
    // Sortable rows
    dragToReorder: "Drag to reorder",
    // Handover summary dialog (tasks)
    handoverSummaryTitle: "Handover summary · {name}",
    handoverSummaryDesc: "Collects in-progress, pending and blocked tasks alongside notes, links and steps. Edit freely before copying or downloading.",
    coverPersonLabel: "Covering person",
    coverPersonPlaceholder: "Temporary owner name",
    expectedReturnLabel: "Expected return",
    annotationsCount: "{count} notes",
    loadingNotes: "Loading notes…",
    closeAction: "Close",
    downloadMd: "Download .md",
    copyAction: "Copy",
    summaryCopied: "Summary copied to clipboard",
    couldNotCopy: "Could not copy",
    couldNotLoadNotes: "Could not load notes",
    handoverOfHeading: "Handover for {name}",
    generatedOn: "Generated on {date}",
    coverLine: "Covered by: {name}",
    returnLine: "Expected return: {date}",
    inProgressHeading: "In progress",
    pendingHeading: "Pending",
    blockedHeading: "Blocked",
    noteByAuthor: "Note ({author})",
    linkWord: "Link",
    stepWord: "Step",
    noOpenTasksItalic: "_No open, in-progress or blocked tasks._",
    // Absence handover summary
    topicCompletedFem: "Completed",
    topicBlockedFem: "Blocked",
    absSickLeaveLabel: "Sick leave",
    teamInline: "Team: {name}",
    roleInline: "Role: {role}",
    absenceInline: "Absence: {type} · {start} → {end}",
    coverInline: "Covered by: {name}",
    noResponsibleInline: "No responsible assigned",
    reassignedFromInline: "Reassigned from: {name}",
    notesInline: "Notes: {text}",
    registeredHandoversTitle: "Registered handovers ({count})",
    noHandoversWarning: "> ⚠️ No handovers registered for this absence.",
    noTopicsItalic: "_No in-progress, pending or blocked topics._",
    handoversWord: "handovers",
    topicsWord: "topics",
    handoverSummaryAbsenceDesc: "Collects in-progress, pending and blocked topics alongside the people covering this person during their absence. Edit freely before copying or downloading.",
    // TaskHandoverNotes
    handoverNotesHeader: "Handover · notes, links and next steps",
    tabNotes: "Notes",
    tabLinks: "Links",
    tabSteps: "Steps",
    loadingShort: "Loading…",
    noNotesYet: "No notes yet.",
    noLinksYet: "No links yet.",
    noStepsYet: "No steps yet.",
    notePlaceholder: "Context, decisions, questions…",
    stepPlaceholder: "Next actionable step…",
    linkTitlePlaceholder: "Link title",
    addNoteBtn: "Add",
    editAria: "Edit",
    deleteAria: "Delete",
    saveAction: "Save",
    cancelAction: "Cancel",
    couldNotSave: "Could not save",
    couldNotDelete: "Could not delete",
    couldNotUpdate: "Could not update",
    // TfsErrorPanel
    tfsErrCors: "TFS network unreachable (is the ROSEN VPN on?)",
    tfsErrMixed: "Blocked by mixed content (HTTP on HTTPS page)",
    tfsErrUnauthorized: "Authentication rejected",
    tfsErrForbidden: "Insufficient permissions",
    tfsErrNotFound: "Resource not found",
    tfsErrTimeout: "Request timed out",
    tfsErrHttp: "HTTP server error",
    tfsErrUnknown: "Connection error",
    tfsErrUrlTested: "URL tested:",
    tfsErrTechDetails: "Technical details",
    tfsHintCors1: "Connect to the ROSEN VPN (or use a machine inside the corporate network). TFS is on-prem and is not reachable from the public internet.",
    tfsHintCors2: "Verify by opening the TFS URL in another tab on the same device: if it doesn't load there either, the VPN/network is not active.",
    tfsHintCors3: "If the TFS URL does load in the browser but fails here, then it's a real CORS issue: ask IT to add Access-Control-Allow-Origin on the IIS / reverse proxy.",
    tfsHintCors4: "If the browser mentions 'CERT': the TFS certificate is not trusted by your browser.",
    tfsHintMixed1: "The app is served over HTTPS but the TFS URL starts with HTTP. Browsers always block this combination.",
    tfsHintMixed2: "Fix: put TFS behind HTTPS (recommended) or serve the app over HTTP (not for production).",
    tfsHintUnauth1: "Generate a new PAT in TFS → Profile → Personal Access Tokens.",
    tfsHintUnauth2: "Make sure it isn't expired and belongs to the same domain as TFS.",
    tfsHintUnauth3: "Some older TFS installations don't accept PATs and require NTLM credentials.",
    tfsHintForb1: "The PAT needs scopes: Work Items (Read), Project & Team (Read), Work (Read).",
    tfsHintForb2: "Confirm your user has access to the project from the TFS web UI.",
    tfsHintNotFound1: "Check the server URL includes /tfs if your install uses it (e.g. https://tfs.company.net/tfs).",
    tfsHintNotFound2: "Verify the exact collection and project names (case sensitive).",
    tfsHintNotFound3: "Open the full URL in the browser to rule out typos.",
    tfsHintTimeout1: "Are you connected to the VPN? Otherwise the internal TFS is unreachable.",
    tfsHintTimeout2: "A corporate firewall may be blocking requests from the browser.",
    tfsHintTimeout3: "Confirm the TFS server is up by opening the URL directly.",
    tfsHintHttp1: "The server responded with an unexpected code. Check the TFS logs.",
    tfsHintHttp2: "Verify that API version (5.0) is compatible with your TFS install.",
    // TfsAutocompleteInput
    tfsAutoSuggestions: "Suggestions",
    tfsAutoFillPrereq: "Fill in the previous fields and the PAT to see suggestions.",
    tfsAutoQuerying: "Querying the TFS server…",
    tfsAutoCanType: "You can still type the value manually.",
    tfsAutoNoServerResults: "No results from the server.",
    tfsAutoNoMatch: "No item matches what you typed.",
    tfsAutoShowSuggestions: "Show suggestions",
    tfsAutoReload: "Reload suggestions",
    tfsAutoLoadError: "Could not load the list.",
    // TfsImportDialog
    tfsImportQuerying: "Querying Azure DevOps...",
    tfsImportSelectAllAvailable: "Select all available ({count})",
    // AppContext toasts
    teamCreatedToast: 'Team "{name}" created',
    teamDeletedToast: 'Team "{name}" deleted',
    invalidHandover: "Invalid handover",
    invalidSchema: "Invalid schema: {msg}",
    importRejectedHandovers: "Import rejected: there are handovers without a topic or with unknown topics.",
    dataImportedOk: "Data imported successfully",
    importPreviewTitle: "Import preview",
    importPreviewDescOk: "Current data will be overwritten with the following:",
    importPreviewDescError: "This file cannot be imported. Fix the following fields and try again:",
    importPreviewNoRecords: "The file is valid but contains no records to import.",
    importPreviewCountTeams: "Teams",
    importPreviewCountMembers: "Members",
    importPreviewCountTopics: "Work topics",
    importPreviewCountAbsences: "Absences",
    importPreviewCountHandovers: "Handovers",
    importPreviewConfirm: "Import and overwrite",
    importPreviewCancel: "Cancel",

    // Pat diagnostics
    patAdvancedTitle: "Advanced PAT diagnostic — {ok}/{total} permissions verified",
    patAllOk: "The PAT has all required permissions.",
    patReviewRed: "Review the permissions marked in red. Each row shows the exact endpoint and the HTTP code returned.",
    patMissingScopes: "Scopes missing from the PAT:",
    patRegenerateHint: "Regenerate the PAT in TFS → Profile → Personal Access Tokens, checking the scopes above.",
    patServerResponse: "Server response",
    patNetworkLabel: "Network",
    // Multi select
    multiSelectSearch: "Search…",
    multiSelectReload: "Reload",
    multiSelectLoading: "Loading…",
    multiSelectSelectedSuffixSingular: "selected",
    multiSelectSelectedSuffixPlural: "selected",
    multiSelectRemoveAria: "Remove {item}",
    multiSelectUnknownError: "Unknown error",
    // CORS guide
    copiedToClipboard: "Copied to clipboard",
    copyAria: "Copy",
    corsViewGuide: "View quick setup guide",
    corsDialogTitle: "Configure CORS on TFS",
    corsDialogDesc: "TFS must reply with CORS headers that allow the origin <ORIGIN>. Ask your IT team to apply one of these snippets to the reverse proxy or IIS in front of TFS.",
    corsIisExplain: "TFS is usually deployed on IIS. Edit the site's web.config and add the block below. Restart the site from IIS Manager after saving.",
    corsIisWarn: "⚠️ If IIS also handles OPTIONS (preflight) requests, make sure OPTIONSVerbHandler is enabled and returns 200/204.",
    corsNginxExplain: "If there is an nginx in front of TFS (reverse proxy), add this block in the server hosting TFS and reload with nginx -s reload.",
    corsApacheExplain: "For Apache httpd as a reverse proxy, make sure mod_headers and mod_rewrite are enabled, and restart the service after saving.",
    corsCheckIntro: "open DevTools → Network,",
    corsCheckTail: "with the header",
    corsSecurityLabel: "Security:",
    corsSecurityBody: "always use a specific origin (not *) when sending credentials.",
    // BugsPage filter
    bugsRemoveIterationFilter: "Remove filter",
    bugsFilterByIteration: "Filter by this iteration",
    bugsClearFiltersTitle: "Clear filters",
    bugsSearchPlaceholder: "Search by title or ID...",
    // AzureDevOps settings
    adoFixFieldsDiagnostics: "Fix the marked fields before running diagnostics.",
    adoAllPermsOk: "✅ All PAT permissions verified",
    adoMissingScopes: "Missing scopes: {scopes}",
    adoSomeChecksFailed: "Some checks failed — review the panel",
    adoDiagnosticsErr: "Diagnostic error",
    adoFixFieldsConnection: "Fix the marked fields before testing the connection.",
    adoDisabledReasonProjects: "Enter server, collection and PAT to list projects.",
    adoDisabledReasonTeams: "Enter server, collection, project and PAT to list teams.",
    adoAdvancedPatCheck: "Advanced PAT check",
    adoLastDiagnostic: "Last diagnostic: {date}",
    adoRodatScopeTitle: "RODAT team scope",
    adoRodatScopeDesc: "Pick the Azure DevOps areas and iterations to load Features and Tasks from. If you pick nothing, the defaults are used",
    adoAreasLabel: "Areas (Features and Tasks)",
    adoSelectAreasPh: "Select one or more areas…",
    adoNoAreasFoundEmpty: "No areas found for this project.",
    adoDisabledReasonAreas: "Configure server, collection, project and PAT to load areas.",
    adoAreasFilterHint: "Features and tasks will be filtered to these areas (including descendants).",
    adoIterationsLabel: "Iterations (Tasks only)",
    adoSelectIterationsPh: "Select one or more iterations…",
    adoNoIterationsFound: "No iterations found for this project.",
    adoDisabledReasonIterations: "Configure server, collection, project and PAT to load iterations.",
    adoIterationsFilterHint: "Tasks will be filtered to these iterations (including descendants).",
    adoBugsQueryLabel: "Bugs query (ID or path)",
    adoBugsQueryPlaceholder: "e.g. 12345678-1234-1234-1234-123456789012 or Shared Queries/Team/Bugs",
    adoBugsQueryHint: "ID (GUID) or path of an existing Azure DevOps query that returns the bugs to show on the Bugs page.",
    adoAutosaved: "Auto-saved · {time}",
    // Features state labels
    stateActive: "Active",
    stateDone: "Done",
    tasksSectionHeading: "Tasks",
    couldNotReadTeamAreas: "Could not read team areas: {error}",
    // Team pulse dashboard
    noAssociatedTasks: "No associated tasks",
    plusMoreSuffix: "+{count} more",
    // Epics
    epics: "Epics",
    epicsPageTitle: "Epics",
    epicsPageDescription: "Epics pulled from Azure DevOps and filtered by the configured tags.",
    epicsTabRoadmap: "Delivery plan",
    epicsTabList: "List",
    epicsEmptyNoSettings: "You haven't configured the Azure DevOps connection yet.",
    epicsEmptyNoTags: "Configure at least one tag in Azure DevOps settings to list Epics.",
    epicsNoResults: "No Epics match the current filters.",
    epicsLoading: "Loading Epics from Azure DevOps...",
    epicsRefresh: "Refresh",
    epicsCount: "epics",
    epicsColId: "ID",
    epicsColTitle: "Title",
    epicsColState: "State",
    epicsColAssignee: "Assigned to",
    epicsColTags: "Tags",
    epicsColArea: "Area",
    epicsColTargetDate: "Target date",
    epicsColChangedDate: "Changed",
    epicsFilterSearch: "Search by title, ID or person...",
    epicsFilterState: "State",
    epicsFilterTag: "Tag",
    epicsFilterTags: "Tags",
    epicsFilterTagsPlaceholder: "All tags",
    epicsFilterTagsSelected: "selected",
    epicsFilterClear: "Clear",
    epicsFilterAll: "All",
    epicsNoDateBucket: "No date",
    epicsUnassigned: "Unassigned",
    epicsOpenSettings: "Open settings",
    epicsTagsConfiguredLabel: "Configured tags",
    epicsEffectiveProjectLabel: "Queried project",
    epicsEffectiveProjectMain: "Main project",
    epicsEffectiveProjectOverride: "Epics project",
    epicsQuarterEpicsSuffix: "epics",
    epicsTabTimeline: "Timeline",
    epicsTabHeatmap: "Heatmap",
    epicsTimelineTodayLabel: "Today",
    epicsTimelineGroupBy: "Group by",
    epicsTimelineNoDatesHint: "No dates",
    epicsTimelineRange4: "4 quarters",
    epicsTimelineRange6: "6 quarters",
    epicsTimelineRange8: "8 quarters",
    epicsGroupNone: "No grouping",
    epicsGroupArea: "Area path",
    epicsGroupAssignee: "Assignee",
    epicsHeatmapRowBy: "Rows by",
    epicsHeatmapNoDateColumn: "No date",
    epicsHeatmapTotal: "Total",
    epicsHeatmapCellDialogTitle: "Epics in cell",
    // Settings — Epics section
    adoEpicsSectionTitle: "Epics",
    adoEpicsSectionDesc: "Configure the source and tags for the Epics view.",
    adoEpicsQueryIdLabel: "Epics query (ID or path)",
    adoEpicsQueryIdPlaceholder: "GUID or Shared Queries/Team/Epics (optional)",
    adoEpicsQueryIdHint: "Optional. If empty, all Epics in the project are listed (optionally restricted by configured area paths).",
    adoEpicsTagsLabel: "Allowed tags",
    adoEpicsTagsPlaceholder: "Type a tag and press Enter",
    adoEpicsTagsHint: "Only Epics that contain any of these tags will be shown.",
    adoEpicsProjectLabel: "Epics project (optional)",
    adoEpicsProjectPlaceholder: "e.g. Software",
    adoEpicsProjectHint: "If the Epics live in another project of the same collection (e.g. 'Software' instead of 'SDES'), set it here. Leave empty to use the main project.",
    adoEpicsProjectSameAsMain: "Same as main project",
    epicsEffectiveTeamLabel: "Team",
    adoEpicsScopeTitle: "Epics scope (Software team)",
    adoEpicsScopeDesc: "Configure a dedicated team, areas and iterations for the Epics view. Leave empty to reuse the main scope.",
    adoEpicsTeamLabel: "Epics team (optional)",
    adoEpicsTeamPlaceholder: "e.g. Software Team",
    adoEpicsTeamHint: "Team within the Epics project. Used as context when resolving saved queries.",
    adoEpicsAreaPathsLabel: "Epics area paths (optional)",
    adoEpicsIterationPathsLabel: "Epics iteration paths (optional)",
    adoEpicsScopeHint: "These values only apply on the Epics view.",
    adoEpicsScopeTestButton: "Test Epics scope",
    adoEpicsScopeTestOk: "Epics scope validated",
    adoEpicsScopeTestPartial: "Connection OK, but some scope values are missing",
    adoEpicsScopeTestTeamsFound: "Teams found",
    adoEpicsScopeTestAreasFound: "Available areas",
    adoEpicsScopeTestIterationsFound: "Available iterations",
    adoEpicsScopeTestTeamMissing: "Configured team not found in project",
    adoEpicsScopeTestAreasMissing: "Configured areas that don't exist",
    adoEpicsScopeTestIterationsMissing: "Configured iterations that don't exist",
    epicDetailCreatedBy: "Created by",
    epicDetailCreated: "Created",
    epicDetailStartDate: "Start date",
    epicDetailIteration: "Iteration",
    epicDetailDescription: "Description",
    epicDetailNoDescription: "No description.",
    epicDetailLinks: "Links and relations",
    epicDetailNoLinks: "No links.",
    epicDetailHistory: "Change history",
    epicDetailNoHistory: "No recorded changes.",
    epicDetailOpenInAdo: "Open in Azure DevOps",
  },

} as const;

type Translations = Record<keyof (typeof translations)["es"], string>;

interface LangState {
  lang: Lang;
  toggleLang: () => void;
  t: Translations;
}

const LanguageContext = createContext<LangState | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("teamflow-lang");
    return saved === "en" ? "en" : "es";
  });

  const toggleLang = () =>
    setLang((l) => {
      const next = l === "es" ? "en" : "es";
      localStorage.setItem("teamflow-lang", next);
      return next;
    });

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
