import React, { createContext, useContext, useState } from "react";

type Lang = "es" | "en";

const translations = {
  es: {
    dashboard: "Dashboard",
    dashboardDesc: "Resumen general de tus equipos",
    searchPeople: "Buscar personas...",
    members: "Miembros",
    absent: "Ausentes",
    upcoming: "Próximas",
    activeHandovers: "Handovers activos",
    noActiveHandovers: "No hay handovers activos en este momento.",
    navigation: "Navegación",
    absences: "Ausencias",
    handovers: "Handovers",
    team: "Equipo",
    // Team page
    teamNotFound: "Equipo no encontrado",
    add: "Añadir",
    newMember: "Nuevo miembro",
    name: "Nombre",
    role: "Rol",
    search: "Buscar...",
    all: "Todos",
    allTeams: "Todos los equipos",
    available: "Disponibles",
    vacation: "Vacaciones",
    sickLeave: "Baja",
    workTopics: "Temas de trabajo",
    addTopic: "Añadir tema",
    topicName: "Nombre del tema...",
    description: "Descripción",
    descPlaceholder: "Descripción...",
    status: "Estado",
    pending: "Pendiente",
    inProgress: "En progreso",
    blocked: "Bloqueado",
    completed: "Completado",
    save: "Guardar",
    create: "Crear",
    noTopics: "Sin temas asignados",
    deleteMember: "Eliminar miembro",
    // Absences page
    absencesDesc: "Gestión de vacaciones y bajas",
    exportCsv: "Exportar CSV",
    newAbsence: "Nueva ausencia",
    editAbsence: "Editar ausencia",
    updateAbsence: "Actualizar ausencia",
    registerAbsence: "Registrar ausencia",
    person: "Persona",
    select: "Seleccionar...",
    type: "Tipo",
    start: "Inicio",
    end: "Fin",
    date: "Fecha",
    register: "Registrar",
    timeline: "Timeline",
    list: "Lista",
    noAbsencesMonth: "Sin ausencias este mes",
    noAbsences: "No hay ausencias registradas.",
    totalDays: "días totales",
    days: "días",
    // Handovers page
    handoversDesc: "Gestión de traspasos de trabajo",
    filterByDate: "Filtrar por fecha",
    from: "Desde",
    to: "Hasta",
    clearFilter: "Limpiar filtro",
    createHandover: "Crear handover",
    newHandover: "Nuevo handover",
    absentPerson: "Persona ausente",
    covers: "Cubre",
    topicsToTransfer: "Temas a traspasar",
    notes: "Notas",
    notesPlaceholder: "Instrucciones para el handover...",
    noHandovers: "No hay handovers creados.",
    editHandover: "Editar handover",
    updateHandover: "Actualizar handover",
    created: "Creado",
    handoverDetail: "Detalle del handover",
    absenceType: "Tipo",
    absencePeriod: "Período de ausencia",
    topicCount: "temas",
    deleteHandoverTitle: "¿Eliminar handover?",
    deleteHandoverDesc: "Esta acción no se puede deshacer. El handover será eliminado permanentemente.",
    deleteAbsenceTitle: "¿Eliminar ausencia?",
    deleteAbsenceDesc: "Esta acción no se puede deshacer. La ausencia será eliminada permanentemente.",
    handoverSelectAbsent: "Selecciona la persona ausente",
    handoverSelectCover: "Selecciona quién cubre",
    handoverSelectTopics: "Selecciona al menos un tema",
    noTopicsAvailable: "Esta persona no tiene temas asignados. Puedes continuar sin seleccionar ninguno.",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmMove: "¿Mover miembro?",
    confirmMoveDesc: "¿Mover a {name} al equipo {team}?",
    confirmDelete: "Eliminar",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Capacidad del equipo",
    analyticsHandoverRate: "Tasa de handover",
    analyticsActiveAbsences: "Ausencias activas",
    analyticsActive: "activos",
    analyticsCurrently: "actualmente",
    analyticsTeamCapacity: "Capacidad por equipo",
    analyticsAbsenceType: "Tipo de ausencia",
    analyticsAbsenceTrend: "Tendencia de ausencias (21 días)",
    analyticsNoData: "Sin datos disponibles",
    analyticsNoAbsences: "Sin ausencias activas",
    // Notifications
    notifTitle: "Notificaciones",
    notifCritical: "críticas",
    notifWarnings: "avisos",
    notifEmpty: "Todo en orden, sin alertas",
    notifNoHandover: "Ausencia sin handover",
    notifNoHandoverDesc: "{name} está ausente sin ningún handover asignado",
    notifUpcomingNoHandover: "Ausencia próxima sin handover",
    notifUpcomingNoHandoverDesc: "{name} se ausenta el {date} y no tiene handover",
    notifCoverageGap: "Brecha de cobertura",
    notifCoverageGapDesc: "{team}: {absent} de {total} miembros ausentes",
    notifUncoveredTopics: "Temas sin cobertura",
    notifUncoveredTopicsDesc: "{count} temas de {name} sin cubrir durante su ausencia",
    // Import absences
    importAbsences: "Importar ausencias",
    importDropzone: "Arrastra un archivo o haz clic para seleccionar",
    importFormats: "CSV, XLSX o XLS",
    importRows: "filas detectadas",
    importChangeFile: "Cambiar archivo",
    importSelectColumn: "Seleccionar columna",
    importPreviewSample: "Vista previa de las primeras filas:",
    importValidate: "Validar datos",
    importValid: "válidas",
    importInvalid: "con errores",
    importBackToMapping: "Volver al mapeo",
    importConfirm: "Importar ausencias",
    importSuccess: "ausencias importadas",
    importParseError: "Error al leer el archivo",
    importEmpty: "El archivo está vacío",
    importUnsupportedFormat: "Formato no soportado. Usa CSV o XLSX",
    importErrNoName: "Sin nombre",
    importErrMemberNotFound: "Miembro no encontrado",
    importErrInvalidType: "Tipo inválido",
    importErrInvalidStart: "Fecha inicio inválida",
    importErrInvalidEnd: "Fecha fin inválida",
    importErrDateOrder: "Inicio posterior al fin",
    // Azure DevOps
    adoTitle: "Azure DevOps",
    adoDesc: "Conecta tu organización de Azure DevOps para sincronizar datos",
    adoConnection: "Conexión",
    adoConnectionDesc: "Introduce tu PAT y datos del proyecto para conectar",
    adoOrganization: "Organización",
    adoOrgHint: "El nombre de tu organización en dev.azure.com/{org}",
    adoProject: "Proyecto",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Necesita permisos: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Probar conexión",
    adoConnectionOk: "Conexión exitosa",
    adoConnectionFailed: "Error de conexión",
    adoFillAllFields: "Completa todos los campos",
    adoLoginRequired: "Inicia sesión para continuar",
    adoTestFirst: "Prueba la conexión primero",
    adoSyncSettings: "Sincronización",
    adoAutoSync: "Sincronización automática",
    adoAutoSyncDesc: "Sincronizar periódicamente con Azure DevOps",
    adoSyncInterval: "Intervalo",
    adoMinutes: "minutos",
    adoHour: "hora",
    adoLastSync: "Última sincronización",
    adoSaveSettings: "Guardar configuración",
    adoUpdateSettings: "Actualizar configuración",
    adoSettingsSaved: "Configuración guardada",
    adoSettingsDeleted: "Configuración eliminada",
    adoDisconnect: "Desconectar",
    // Not found
    pageNotFound: "Oops! Página no encontrada",
    returnHome: "Volver al inicio",
  },
  en: {
    dashboard: "Dashboard",
    dashboardDesc: "General overview of your teams",
    searchPeople: "Search people...",
    members: "Members",
    absent: "Absent",
    upcoming: "Upcoming",
    activeHandovers: "Active handovers",
    noActiveHandovers: "No active handovers at this time.",
    navigation: "Navigation",
    absences: "Absences",
    handovers: "Handovers",
    team: "Team",
    // Team page
    teamNotFound: "Team not found",
    add: "Add",
    newMember: "New member",
    name: "Name",
    role: "Role",
    search: "Search...",
    all: "All",
    allTeams: "All teams",
    available: "Available",
    vacation: "Vacation",
    sickLeave: "Sick leave",
    workTopics: "Work topics",
    addTopic: "Add topic",
    topicName: "Topic name...",
    description: "Description",
    descPlaceholder: "Description...",
    status: "Status",
    pending: "Pending",
    inProgress: "In progress",
    blocked: "Blocked",
    completed: "Completed",
    save: "Save",
    create: "Create",
    noTopics: "No assigned topics",
    deleteMember: "Delete member",
    // Absences page
    absencesDesc: "Vacation and leave management",
    exportCsv: "Export CSV",
    newAbsence: "New absence",
    editAbsence: "Edit absence",
    updateAbsence: "Update absence",
    registerAbsence: "Register absence",
    person: "Person",
    select: "Select...",
    type: "Type",
    start: "Start",
    end: "End",
    date: "Date",
    register: "Register",
    timeline: "Timeline",
    list: "List",
    noAbsencesMonth: "No absences this month",
    noAbsences: "No absences registered.",
    totalDays: "total days",
    days: "days",
    // Handovers page
    handoversDesc: "Work handover management",
    filterByDate: "Filter by date",
    from: "From",
    to: "To",
    clearFilter: "Clear filter",
    createHandover: "Create handover",
    newHandover: "New handover",
    absentPerson: "Absent person",
    covers: "Covers",
    topicsToTransfer: "Topics to transfer",
    notes: "Notes",
    notesPlaceholder: "Instructions for the handover...",
    noHandovers: "No handovers created.",
    editHandover: "Edit handover",
    updateHandover: "Update handover",
    created: "Created",
    handoverDetail: "Handover detail",
    absenceType: "Type",
    absencePeriod: "Absence period",
    topicCount: "topics",
    deleteHandoverTitle: "Delete handover?",
    deleteHandoverDesc: "This action cannot be undone. The handover will be permanently deleted.",
    deleteAbsenceTitle: "Delete absence?",
    deleteAbsenceDesc: "This action cannot be undone. The absence will be permanently deleted.",
    handoverSelectAbsent: "Select the absent person",
    handoverSelectCover: "Select who covers",
    handoverSelectTopics: "Select at least one topic",
    noTopicsAvailable: "This person has no assigned topics. You can continue without selecting any.",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmMove: "Move member?",
    confirmMoveDesc: "Move {name} to {team}?",
    confirmDelete: "Delete",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Team capacity",
    analyticsHandoverRate: "Handover rate",
    analyticsActiveAbsences: "Active absences",
    analyticsActive: "active",
    analyticsCurrently: "currently",
    analyticsTeamCapacity: "Capacity by team",
    analyticsAbsenceType: "Absence type",
    analyticsAbsenceTrend: "Absence trend (21 days)",
    analyticsNoData: "No data available",
    analyticsNoAbsences: "No active absences",
    // Notifications
    notifTitle: "Notifications",
    notifCritical: "critical",
    notifWarnings: "warnings",
    notifEmpty: "All clear, no alerts",
    notifNoHandover: "Absence without handover",
    notifNoHandoverDesc: "{name} is absent with no handover assigned",
    notifUpcomingNoHandover: "Upcoming absence without handover",
    notifUpcomingNoHandoverDesc: "{name} will be absent on {date} with no handover",
    notifCoverageGap: "Coverage gap",
    notifCoverageGapDesc: "{team}: {absent} of {total} members absent",
    notifUncoveredTopics: "Uncovered topics",
    notifUncoveredTopicsDesc: "{count} topics from {name} uncovered during absence",
    // Import absences
    importAbsences: "Import absences",
    importDropzone: "Drag a file or click to select",
    importFormats: "CSV, XLSX or XLS",
    importRows: "rows detected",
    importChangeFile: "Change file",
    importSelectColumn: "Select column",
    importPreviewSample: "Preview of first rows:",
    importValidate: "Validate data",
    importValid: "valid",
    importInvalid: "with errors",
    importBackToMapping: "Back to mapping",
    importConfirm: "Import absences",
    importSuccess: "absences imported",
    importParseError: "Error reading file",
    importEmpty: "File is empty",
    importUnsupportedFormat: "Unsupported format. Use CSV or XLSX",
    importErrNoName: "No name",
    importErrMemberNotFound: "Member not found",
    importErrInvalidType: "Invalid type",
    importErrInvalidStart: "Invalid start date",
    importErrInvalidEnd: "Invalid end date",
    importErrDateOrder: "Start after end",
    // Azure DevOps
    adoTitle: "Azure DevOps",
    adoDesc: "Connect your Azure DevOps organization to sync data",
    adoConnection: "Connection",
    adoConnectionDesc: "Enter your PAT and project details to connect",
    adoOrganization: "Organization",
    adoOrgHint: "Your organization name at dev.azure.com/{org}",
    adoProject: "Project",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Requires permissions: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Test connection",
    adoConnectionOk: "Connection successful",
    adoConnectionFailed: "Connection failed",
    adoFillAllFields: "Fill in all fields",
    adoLoginRequired: "Log in to continue",
    adoTestFirst: "Test the connection first",
    adoSyncSettings: "Synchronization",
    adoAutoSync: "Auto sync",
    adoAutoSyncDesc: "Periodically sync with Azure DevOps",
    adoSyncInterval: "Interval",
    adoMinutes: "minutes",
    adoHour: "hour",
    adoLastSync: "Last sync",
    adoSaveSettings: "Save settings",
    adoUpdateSettings: "Update settings",
    adoSettingsSaved: "Settings saved",
    adoSettingsDeleted: "Settings deleted",
    adoDisconnect: "Disconnect",
    // Not found
    pageNotFound: "Oops! Page not found",
    returnHome: "Return to Home",
  },
} as const;

type Translations = Record<keyof (typeof translations)["es"], string>;

interface LangState {
  lang: Lang;
  toggleLang: () => void;
  t: Translations;
}

const LanguageContext = createContext<LangState | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("teamflow-lang");
    return saved === "en" ? "en" : "es";
  });

  const toggleLang = () =>
    setLang((l) => {
      const next = l === "es" ? "en" : "es";
      localStorage.setItem("teamflow-lang", next);
      return next;
    });

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
