import React, { createContext, useContext, useState } from "react";

type Lang = "es" | "en";

const translations = {
  es: {
    dashboard: "Dashboard",
    dashboardDesc: "Resumen general de tus equipos",
    searchPeople: "Buscar personas...",
    members: "Miembros",
    absent: "Ausentes",
    upcoming: "Próximas",
    activeHandovers: "Handovers activos",
    noActiveHandovers: "No hay handovers activos en este momento.",
    navigation: "Navegación",
    absences: "Ausencias",
    handovers: "Handovers",
    features: "Features",
    tasks: "Tareas",
    workload: "Carga & Capacidad",
    featuresAndTasks: "Features & Tareas",
    team: "Equipo",
    // Team page
    teamNotFound: "Equipo no encontrado",
    add: "Añadir",
    newMember: "Nuevo miembro",
    name: "Nombre",
    role: "Rol",
    search: "Buscar...",
    all: "Todos",
    allTeams: "Todos los equipos",
    allTypes: "Todos los tipos",
    available: "Disponibles",
    vacation: "Vacaciones",
    sickLeave: "Baja",
    workTravel: "Viaje de trabajo",
    otherProject: "Otro proyecto",
    parentalLeave: "Baja parental",
    workTopics: "Temas de trabajo",
    addTopic: "Añadir tema",
    topicName: "Nombre del tema...",
    description: "Descripción",
    descPlaceholder: "Descripción...",
    status: "Estado",
    pending: "Pendiente",
    inProgress: "En progreso",
    blocked: "Bloqueado",
    completed: "Completado",
    save: "Guardar",
    create: "Crear",
    noTopics: "Sin temas asignados",
    deleteMember: "Eliminar miembro",
    errSelectMember: "Selecciona al menos un miembro",
    errInvalidMaxCapacity: "Capacidad máxima inválida",
    errInvalidBaseCapacity: "Capacidad base inválida",
    errBaseGtMax: "La capacidad base no puede ser mayor que la capacidad máxima",
    errBulkConflict: "Para algunos miembros, la nueva configuración hace que la capacidad base supere a la máxima. Revisa los valores.",
    capacityUpdated: "Capacidad actualizada para {count} miembros",
    errNameMinLength: "El nombre debe tener al menos 2 caracteres",
    errRoleMinLength: "El rol debe tener al menos 2 caracteres",
    errMaxLtBase: "La capacidad máxima no puede ser menor que la base",
    errBaseGtMaxSingle: "La capacidad base no puede ser mayor que la máxima",
    resetCapacityConfirmTitle: "¿Restablecer capacidad?",
    resetCapacityConfirmDesc: "¿Estás seguro de que quieres restablecer la capacidad de {name} a los valores por defecto (Máx: 40h, Base: 32h)?",
    resetCapacity: "Restablecer",
    undo: "Deshacer",
    capacityResetSuccess: "Capacidad restablecida",
    capacityConfig: "Configuración de Capacidad",
    maxCapacity: "Capacidad Máxima (h/sem)",
    baseCapacity: "Capacidad Base (h/sem)",
    // Absences page
    absencesDesc: "Gestión de vacaciones y bajas",
    exportCsv: "Exportar CSV",
    newAbsence: "Nueva ausencia",
    editAbsence: "Editar ausencia",
    updateAbsence: "Actualizar ausencia",
    registerAbsence: "Registrar ausencia",
    person: "Persona",
    select: "Seleccionar...",
    type: "Tipo",
    start: "Inicio",
    end: "Fin",
    date: "Fecha",
    register: "Registrar",
    timeline: "Timeline",
    list: "Lista",
    noAbsencesMonth: "Sin ausencias este mes",
    noAbsences: "No hay ausencias registradas.",
    totalDays: "días totales",
    days: "días",
    // Handovers page
    handoversDesc: "Gestión de traspasos de trabajo",
    filterByDate: "Filtrar por fecha",
    from: "Desde",
    to: "Hasta",
    clearFilter: "Limpiar filtro",
    createHandover: "Crear handover",
    newHandover: "Nuevo handover",
    absentPerson: "Persona ausente",
    covers: "Cubre",
    topicsToTransfer: "Temas a traspasar",
    notes: "Notas",
    notesPlaceholder: "Instrucciones para el handover...",
    noHandovers: "No hay handovers creados.",
    editHandover: "Editar handover",
    updateHandover: "Actualizar handover",
    created: "Creado",
    handoverDetail: "Detalle del handover",
    absenceType: "Tipo",
    absencePeriod: "Período de ausencia",
    topicCount: "temas",
    deleteHandoverTitle: "¿Eliminar handover?",
    deleteHandoverDesc: "Esta acción no se puede deshacer. El handover será eliminado permanentemente.",
    deleteAbsenceTitle: "¿Eliminar ausencia?",
    deleteAbsenceDesc: "Esta acción no se puede deshacer. La ausencia será eliminada permanentemente.",
    handoverSelectAbsent: "Selecciona la persona ausente",
    handoverSelectCover: "Selecciona quién cubre",
    handoverSelectTopics: "Selecciona al menos un tema",
    noTopicsAvailable: "Esta persona no tiene temas asignados. Puedes continuar sin seleccionar ninguno.",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmMove: "¿Mover miembro?",
    confirmMoveDesc: "¿Mover a {name} al equipo {team}?",
    confirmDelete: "Eliminar",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Capacidad del equipo",
    analyticsHandoverRate: "Tasa de handover",
    analyticsActiveAbsences: "Ausencias activas",
    analyticsActive: "activos",
    analyticsCurrently: "actualmente",
    analyticsTeamCapacity: "Capacidad por equipo",
    analyticsAbsenceType: "Tipo de ausencia",
    analyticsAbsenceTrend: "Tendencia de ausencias (21 días)",
    analyticsNoData: "Sin datos disponibles",
    analyticsNoAbsences: "Sin ausencias activas",
    // Notifications
    notifTitle: "Notificaciones",
    notifCritical: "críticas",
    notifWarnings: "avisos",
    notifEmpty: "Todo en orden, sin alertas",
    notifNoHandover: "Ausencia sin handover",
    notifNoHandoverDesc: "{name} está ausente sin ningún handover asignado",
    notifUpcomingNoHandover: "Ausencia próxima sin handover",
    notifUpcomingNoHandoverDesc: "{name} se ausenta el {date} y no tiene handover",
    notifCoverageGap: "Brecha de cobertura",
    notifCoverageGapDesc: "{team}: {absent} de {total} miembros ausentes",
    notifUncoveredTopics: "Temas sin cobertura",
    notifUncoveredTopicsDesc: "{count} temas de {name} sin cubrir durante su ausencia",
    // Import absences
    importAbsences: "Importar ausencias",
    importDropzone: "Arrastra un archivo o haz clic para seleccionar",
    importFormats: "CSV, XLSX o XLS",
    importRows: "filas detectadas",
    importChangeFile: "Cambiar archivo",
    importSelectColumn: "Seleccionar columna",
    importPreviewSample: "Vista previa de las primeras filas:",
    importValidate: "Validar datos",
    importValid: "válidas",
    importInvalid: "con errores",
    importBackToMapping: "Volver al mapeo",
    importConfirm: "Importar ausencias",
    importSuccess: "ausencias importadas",
    importParseError: "Error al leer el archivo",
    importEmpty: "El archivo está vacío",
    importUnsupportedFormat: "Formato no soportado. Usa CSV o XLSX",
    importErrNoName: "Sin nombre",
    importErrMemberNotFound: "Miembro no encontrado",
    importErrInvalidType: "Tipo inválido",
    importErrInvalidStart: "Fecha inicio inválida",
    importErrInvalidEnd: "Fecha fin inválida",
    importErrDateOrder: "Inicio posterior al fin",
    // Azure DevOps / TFS
    adoTitle: "Azure DevOps / TFS",
    adoDesc: "Conecta con Azure DevOps Server (TFS on-premise) o Azure DevOps cloud",
    adoConnection: "Conexión",
    adoConnectionDesc: "Introduce los datos de tu servidor TFS y un PAT con permisos de lectura",
    adoServerUrl: "URL del servidor",
    adoServerUrlHint: "Ej. https://tfs.empresa.net/tfs (sin la colección)",
    adoCollection: "Colección",
    adoCollectionHint: "Nombre de la colección de proyectos en TFS (ej. RNDCollection)",
    adoOrganization: "Organización (cloud)",
    adoOrgHint: "Solo para Azure DevOps cloud (dev.azure.com/{org}). Déjalo vacío para TFS on-premise.",
    adoProject: "Proyecto",
    adoTeam: "Equipo (opcional)",
    adoTeamHint: "Filtra por equipo dentro del proyecto, si aplica",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Necesita permisos: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Probar conexión",
    adoConnectionOk: "Conexión exitosa",
    adoConnectionFailed: "Error de conexión",
    adoFillAllFields: "Completa los campos obligatorios (URL, colección, proyecto y PAT)",
    adoLoginRequired: "Inicia sesión para continuar",
    adoTestFirst: "Prueba la conexión primero",
    adoSyncSettings: "Sincronización",
    adoAutoSync: "Sincronización automática",
    adoAutoSyncDesc: "Sincronizar periódicamente con TFS",
    adoSyncInterval: "Intervalo",
    adoMinutes: "minutos",
    adoHour: "hora",
    adoLastSync: "Última sincronización",
    adoSaveSettings: "Guardar configuración",
    adoUpdateSettings: "Actualizar configuración",
    adoSettingsSaved: "Configuración guardada",
    adoSettingsDeleted: "Configuración eliminada",
    adoDisconnect: "Desconectar",
    adoNetworkWarningTitle: "Requiere acceso a la red corporativa",
    adoNetworkWarningBody: "La conexión se hace directamente desde tu navegador al servidor TFS. Necesitas estar en la red interna o conectado por VPN, y el TFS debe permitir CORS desde el origen de esta app.",
    // Auth
    authLogin: "Iniciar sesión",
    authSignup: "Crear cuenta",
    authPassword: "Contraseña",
    authSubtitle: "Gestión de handovers y equipos",
    authNamePlaceholder: "Tu nombre",
    authLoginSuccess: "Sesión iniciada",
    authSignupSuccess: "Cuenta creada correctamente",
    authPasswordMin: "La contraseña debe tener al menos 6 caracteres",
    authForgotPassword: "¿Olvidaste tu contraseña?",
    authResetPassword: "Restablecer contraseña",
    authResetDesc: "Introduce tu email y te enviaremos un enlace",
    authSendReset: "Enviar enlace",
    authResetSent: "Enlace enviado, revisa tu bandeja de entrada",
    authBackToLogin: "Volver al inicio de sesión",
    authNewPassword: "Nueva contraseña",
    authNewPasswordDesc: "Introduce tu nueva contraseña",
    authUpdatePassword: "Actualizar contraseña",
    authPasswordUpdated: "Contraseña actualizada correctamente",
    authInvalidResetLink: "Enlace de restablecimiento no válido o expirado",
    authLogout: "Cerrar sesión",
    bulkCapacityEditTitle: "Edición en Bloque de Capacidades",
    preloadingAreas: "Precargando áreas…",
    usingCache: "Usando caché",
    statusDistribution: "Distribución por estado",
    statusDistributionDesc: "Qué se está ejecutando ahora mismo",
    topTasks: "Top {count} con más tareas",
    cache: "Caché",
    moreTasks: "Más tareas",
    lessTasks: "Menos tareas",
    defaultSort: "Por defecto",
    sortBy: "Ordenar por",
    title: "Título",
    noArea: "(sin área)",
    noIteration: "(sin iteración)",
    noTitle: "(sin título)",
    outOfScopeHidden: "Elementos fuera del alcance ocultos automáticamente",
    errTeamAreasUpdate: "No se pudo actualizar la lista de áreas del equipo. Se está usando la última versión en caché.",
    errPeopleUpdate: "No se pudo actualizar la lista de personas. Se está mostrando el último listado en caché.",
    errIncompleteAdoConfig: "Configuración de Azure DevOps incompleta. Mostrando datos locales.",
    hideHandover: "Ocultar handover",
    addHandover: "Añadir handover",
    tasksSubtitle: "Trabajo asignado por persona, abierto y en progreso.",
    featuresSubtitle: "Iniciativas del proyecto y su progreso global.",
    generalOverview: "Visión general del trabajo en curso del proyecto.",
    workloadSubtitle: "Disponibilidad y carga de trabajo agrupada por semana (solo tareas In Progress).",
    workloadSubtitleAll: "Disponibilidad y carga de trabajo agrupada por semana (todas las tareas activas).",
    taskDetailInProgress: "Detalle de Tareas (In Progress) - {name}",
    taskDetailAll: "Detalle de Tareas (Todas) - {name}",
    inProgressTasksCount: "{count} In Progress",
    allTasksCount: "{count} Tareas",
    onlyInProgress: "Solo In Progress",
    allTasks: "Todas las tareas",
    addTeam: "Añadir equipo",
    ongoing: "En curso",
    upcomingStatus: "Próximo",
    checkHowTo: "Cómo verificar:",
    checkCorsDetails: "pulsa Probar conexión y comprueba que la petición OPTIONS (preflight) recibe",
    adoAreas: "Áreas (Features y Tareas)",
    errFieldsDiagnostics: "Corrige los campos marcados antes de ejecutar el diagnóstico.",
    errDiagnostics: "Error en diagnóstico",
    errFieldsConnection: "Corrige los campos marcados antes de probar la conexión.",
    errAdoProjects: "Introduce servidor, colección y PAT para listar proyectos.",
    errAdoTeams: "Introduce servidor, colección, proyecto y PAT para listar equipos.",
    adoSelectAreas: "Selecciona una o varias áreas…",
    adoNoAreasFound: "No se encontraron áreas para este proyecto.",
    errAdoLoadAreas: "Configura servidor, colección, proyecto y PAT para cargar las áreas.",
    errAdoLoadIterations: "Configura servidor, colección, proyecto y PAT para cargar las iteraciones.",
    errImportInvalidJson: "Error al importar: archivo JSON inválido",
    confirmImportOverwrite: "¿Estás seguro? Esto sobrescribirá todos los datos actuales con los del archivo seleccionado.",
    writeSomething: "Escribe algo",
    max2000Chars: "Máximo 2000 caracteres",
    invalidUrl: "URL inválida",
    urlTooLong: "URL demasiado larga",
    mustBeLoggedIn: "Debes iniciar sesión",
    anonymous: "Anónimo",
    noteAdded: "Anotación añadida",
    noMatchingItems: "Ningún elemento coincide con lo escrito.",
    // Not found
    pageNotFound: "Oops! Página no encontrada",
    returnHome: "Volver al inicio",
    workloadAndCapacity: "Carga de Trabajo y Disponibilidad",
    allMembers: "Todos los miembros",
    selectedCount: "{count} seleccionados",
    searchMember: "Buscar miembro...",
    noResults: "No hay resultados.",
    weeks: "Semanas",
    nWeeks: "{count} Semanas",
    member: "Miembro",
    weekDate: "Semana {date}",
    effortHours: "Esfuerzo: {hours}h",
    noTasksThisWeek: "No hay tareas asignadas para esta semana.",
    filtersApplied: "Filtros aplicados a las consultas de Features y Tareas. Cámbialos en Ajustes › Azure DevOps.",
    iterationsTasks: "Iteraciones (Tareas)",
    featureCount: "{count} feature",
    featuresCount: "{count} features",
    taskCount: "{count} tarea",
    tasksCountPlural: "{count} tareas",
    featuresOutOfArea: "Features fuera del área ({count})",
    tasksOutOfArea: "Tareas fuera del área ({count})",
    tasksOutOfIteration: "Tareas fuera de la iteración ({count})",
    projectFeatures: "Features del proyecto",
    featureProgress: "Progreso por feature con tareas asociadas",
    noFeaturesToShow: "No hay features para mostrar.",
    tasksRatio: "{done} / {total} tareas",
    loadPerPerson: "Carga por persona",
    tasksPerPerson: "Tareas por persona",
    fetchAreasError: "No se pudieron leer las áreas del equipo: {error}",
    unassigned: "Sin asignar",
    effectiveScope: "Alcance efectivo",
    resultWithScope: "Resultado con este alcance",
    noCustomScope: "No hay alcance personalizado en Ajustes; se usan los valores por defecto del equipo RODAT.",
    showingXofYFeatures: "Mostrando {x} de {y} features",
    showingXofYTasks: "Mostrando {x} de {y} tareas",
    excludedOutOfAreaFeatures: "Excluidas: {count} features fuera del área,",
    excludedOutOfAreaTasks: " {count} tareas fuera del área,",
    excludedOutOfIterTasks: " {count} tareas fuera de la iteración.",
    viewHiddenAudit: "Ver auditoría de elementos ocultos",
    area: "Área",
    iterationTasks: "Iteración (tareas)",
    expectedUnder: "Esperado bajo {paths}",
    copyLinkTask: "Copiar enlace de la tarea {id}",
    copyLinkFeature: "Copiar enlace de la feature {id}",
    linkCopied: "Enlace de la {type} #{id} copiado",
    linkCopyFailed: "No se pudo copiar el enlace",
    workDistribution: "Distribución del trabajo por persona — solo abiertas y en progreso.",
    personCount: "{count} persona",
    personsCount: "{count} personas",
    filtering: "filtrando",
    inProgressPlural: "en progreso",
    pendingPlural: "pendientes",
    blockedPlural: "bloqueadas",
    completedPlural: "completadas",
    confirmChangesBeforeApply: "Confirmar cambios antes de aplicar",
    unappliedChanges: "Cambios sin aplicar",
    discard: "Descartar",
    apply: "Aplicar",
    viewByPerson: "Vista por persona",
    viewFlatList: "Ver listado plano",
    showingMaxOf: "Mostrando {max} de {total} tareas — afina los filtros para ver más.",
    noPersonsMatching: "No hay personas con tareas que coincidan con los filtros actuales.",
    allPersons: "Todas las personas",
    allPersonsCount: "Todas las personas ({count})",
    searchPerson: "Buscar persona...",
  },
  en: {
    dashboard: "Dashboard",
    dashboardDesc: "General overview of your teams",
    searchPeople: "Search people...",
    members: "Members",
    absent: "Absent",
    upcoming: "Upcoming",
    activeHandovers: "Active handovers",
    noActiveHandovers: "No active handovers at this time.",
    navigation: "Navigation",
    absences: "Absences",
    handovers: "Handovers",
    features: "Features",
    tasks: "Tasks",
    workload: "Workload & Capacity",
    featuresAndTasks: "Features & Tasks",
    team: "Team",
    // Team page
    teamNotFound: "Team not found",
    add: "Add",
    newMember: "New member",
    name: "Name",
    role: "Role",
    search: "Search...",
    all: "All",
    allTeams: "All teams",
    allTypes: "All types",
    available: "Available",
    vacation: "Vacation",
    sickLeave: "Sick leave",
    workTravel: "Work travel",
    otherProject: "Other project",
    parentalLeave: "Parental leave",
    workTopics: "Work topics",
    addTopic: "Add topic",
    topicName: "Topic name...",
    description: "Description",
    descPlaceholder: "Description...",
    status: "Status",
    pending: "Pending",
    inProgress: "In progress",
    blocked: "Blocked",
    completed: "Completed",
    save: "Save",
    create: "Create",
    noTopics: "No assigned topics",
    deleteMember: "Delete member",
    errSelectMember: "Select at least one member",
    errInvalidMaxCapacity: "Invalid max capacity",
    errInvalidBaseCapacity: "Invalid base capacity",
    errBaseGtMax: "Base capacity cannot be greater than max capacity",
    errBulkConflict: "For some members, the new configuration causes base capacity to exceed max capacity. Please review the values.",
    capacityUpdated: "Capacity updated for {count} members",
    errNameMinLength: "Name must be at least 2 characters",
    errRoleMinLength: "Role must be at least 2 characters",
    errMaxLtBase: "Max capacity cannot be less than base capacity",
    errBaseGtMaxSingle: "Base capacity cannot be greater than max capacity",
    resetCapacityConfirmTitle: "Reset capacity?",
    resetCapacityConfirmDesc: "Are you sure you want to reset {name}'s capacity to default values (Max: 40h, Base: 32h)?",
    resetCapacity: "Reset",
    undo: "Undo",
    capacityResetSuccess: "Capacity reset successfully",
    capacityConfig: "Capacity Configuration",
    maxCapacity: "Max Capacity (h/week)",
    baseCapacity: "Base Capacity (h/week)",
    // Absences page
    absencesDesc: "Vacation and leave management",
    exportCsv: "Export CSV",
    newAbsence: "New absence",
    editAbsence: "Edit absence",
    updateAbsence: "Update absence",
    registerAbsence: "Register absence",
    person: "Person",
    select: "Select...",
    type: "Type",
    start: "Start",
    end: "End",
    date: "Date",
    register: "Register",
    timeline: "Timeline",
    list: "List",
    noAbsencesMonth: "No absences this month",
    noAbsences: "No absences registered.",
    totalDays: "total days",
    days: "days",
    // Handovers page
    handoversDesc: "Work handover management",
    filterByDate: "Filter by date",
    from: "From",
    to: "To",
    clearFilter: "Clear filter",
    createHandover: "Create handover",
    newHandover: "New handover",
    absentPerson: "Absent person",
    covers: "Covers",
    topicsToTransfer: "Topics to transfer",
    notes: "Notes",
    notesPlaceholder: "Instructions for the handover...",
    noHandovers: "No handovers created.",
    editHandover: "Edit handover",
    updateHandover: "Update handover",
    created: "Created",
    handoverDetail: "Handover detail",
    absenceType: "Type",
    absencePeriod: "Absence period",
    topicCount: "topics",
    deleteHandoverTitle: "Delete handover?",
    deleteHandoverDesc: "This action cannot be undone. The handover will be permanently deleted.",
    deleteAbsenceTitle: "Delete absence?",
    deleteAbsenceDesc: "This action cannot be undone. The absence will be permanently deleted.",
    handoverSelectAbsent: "Select the absent person",
    handoverSelectCover: "Select who covers",
    handoverSelectTopics: "Select at least one topic",
    noTopicsAvailable: "This person has no assigned topics. You can continue without selecting any.",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmMove: "Move member?",
    confirmMoveDesc: "Move {name} to {team}?",
    confirmDelete: "Delete",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsCapacity: "Team capacity",
    analyticsHandoverRate: "Handover rate",
    analyticsActiveAbsences: "Active absences",
    analyticsActive: "active",
    analyticsCurrently: "currently",
    analyticsTeamCapacity: "Capacity by team",
    analyticsAbsenceType: "Absence type",
    analyticsAbsenceTrend: "Absence trend (21 days)",
    analyticsNoData: "No data available",
    analyticsNoAbsences: "No active absences",
    // Notifications
    notifTitle: "Notifications",
    notifCritical: "critical",
    notifWarnings: "warnings",
    notifEmpty: "All clear, no alerts",
    notifNoHandover: "Absence without handover",
    notifNoHandoverDesc: "{name} is absent with no handover assigned",
    notifUpcomingNoHandover: "Upcoming absence without handover",
    notifUpcomingNoHandoverDesc: "{name} will be absent on {date} with no handover",
    notifCoverageGap: "Coverage gap",
    notifCoverageGapDesc: "{team}: {absent} of {total} members absent",
    notifUncoveredTopics: "Uncovered topics",
    notifUncoveredTopicsDesc: "{count} topics from {name} uncovered during absence",
    // Import absences
    importAbsences: "Import absences",
    importDropzone: "Drag a file or click to select",
    importFormats: "CSV, XLSX or XLS",
    importRows: "rows detected",
    importChangeFile: "Change file",
    importSelectColumn: "Select column",
    importPreviewSample: "Preview of first rows:",
    importValidate: "Validate data",
    importValid: "valid",
    importInvalid: "with errors",
    importBackToMapping: "Back to mapping",
    importConfirm: "Import absences",
    importSuccess: "absences imported",
    importParseError: "Error reading file",
    importEmpty: "File is empty",
    importUnsupportedFormat: "Unsupported format. Use CSV or XLSX",
    importErrNoName: "No name",
    importErrMemberNotFound: "Member not found",
    importErrInvalidType: "Invalid type",
    importErrInvalidStart: "Invalid start date",
    importErrInvalidEnd: "Invalid end date",
    importErrDateOrder: "Start after end",
    // Azure DevOps / TFS
    adoTitle: "Azure DevOps / TFS",
    adoDesc: "Connect to Azure DevOps Server (on-premise TFS) or Azure DevOps cloud",
    adoConnection: "Connection",
    adoConnectionDesc: "Enter your TFS server details and a PAT with read permissions",
    adoServerUrl: "Server URL",
    adoServerUrlHint: "E.g. https://tfs.company.net/tfs (without the collection)",
    adoCollection: "Collection",
    adoCollectionHint: "Project collection name in TFS (e.g. RNDCollection)",
    adoOrganization: "Organization (cloud)",
    adoOrgHint: "Only for Azure DevOps cloud (dev.azure.com/{org}). Leave empty for on-premise TFS.",
    adoProject: "Project",
    adoTeam: "Team (optional)",
    adoTeamHint: "Filter by team inside the project, if applicable",
    adoPat: "Personal Access Token (PAT)",
    adoPatHint: "Requires permissions: Work Items (Read), Project & Team (Read), Work (Read)",
    adoTestConnection: "Test connection",
    adoConnectionOk: "Connection successful",
    adoConnectionFailed: "Connection failed",
    adoFillAllFields: "Fill in the required fields (URL, collection, project and PAT)",
    adoLoginRequired: "Log in to continue",
    adoTestFirst: "Test the connection first",
    adoSyncSettings: "Synchronization",
    adoAutoSync: "Auto sync",
    adoAutoSyncDesc: "Periodically sync with TFS",
    adoSyncInterval: "Interval",
    adoMinutes: "minutes",
    adoHour: "hour",
    adoLastSync: "Last sync",
    adoSaveSettings: "Save settings",
    adoUpdateSettings: "Update settings",
    adoSettingsSaved: "Settings saved",
    adoSettingsDeleted: "Settings deleted",
    adoDisconnect: "Disconnect",
    adoNetworkWarningTitle: "Requires corporate network access",
    adoNetworkWarningBody: "The connection runs directly from your browser to the TFS server. You must be on the internal network or connected via VPN, and TFS must allow CORS from this app's origin.",
    // Auth
    authLogin: "Log in",
    authSignup: "Sign up",
    authPassword: "Password",
    authSubtitle: "Handover and team management",
    authNamePlaceholder: "Your name",
    authLoginSuccess: "Logged in",
    authSignupSuccess: "Account created successfully",
    authPasswordMin: "Password must be at least 6 characters",
    authForgotPassword: "Forgot your password?",
    authResetPassword: "Reset password",
    authResetDesc: "Enter your email and we'll send you a link",
    authSendReset: "Send link",
    authResetSent: "Link sent, check your inbox",
    authBackToLogin: "Back to login",
    authNewPassword: "New password",
    authNewPasswordDesc: "Enter your new password",
    authUpdatePassword: "Update password",
    authPasswordUpdated: "Password updated successfully",
    authInvalidResetLink: "Invalid or expired reset link",
    authLogout: "Log out",
    bulkCapacityEditTitle: "Bulk Capacity Edit",
    preloadingAreas: "Preloading areas...",
    usingCache: "Using cache",
    statusDistribution: "Status distribution",
    statusDistributionDesc: "What is currently running",
    topTasks: "Top {count} with most tasks",
    cache: "Cache",
    moreTasks: "More tasks",
    lessTasks: "Fewer tasks",
    defaultSort: "Default",
    sortBy: "Sort by",
    title: "Title",
    noArea: "(no area)",
    noIteration: "(no iteration)",
    noTitle: "(no title)",
    outOfScopeHidden: "Out-of-scope items automatically hidden",
    errTeamAreasUpdate: "Failed to update team areas list. Using latest cached version.",
    errPeopleUpdate: "Failed to update people list. Showing latest cached list.",
    errIncompleteAdoConfig: "Incomplete Azure DevOps configuration. Showing local data.",
    hideHandover: "Hide handover",
    addHandover: "Add handover",
    tasksSubtitle: "Assigned work per person, open and in progress.",
    featuresSubtitle: "Project initiatives and their overall progress.",
    generalOverview: "General overview of the project's ongoing work.",
    workloadSubtitle: "Availability and workload grouped by week (only In Progress tasks).",
    workloadSubtitleAll: "Availability and workload grouped by week (all active tasks).",
    taskDetailInProgress: "Task Details (In Progress) - {name}",
    taskDetailAll: "Task Details (All) - {name}",
    inProgressTasksCount: "{count} In Progress",
    allTasksCount: "{count} Tasks",
    onlyInProgress: "Only In Progress",
    allTasks: "All tasks",
    addTeam: "Add team",
    ongoing: "Ongoing",
    upcomingStatus: "Upcoming",
    checkHowTo: "How to check:",
    checkCorsDetails: "click Test connection and check that the OPTIONS (preflight) request receives",
    adoAreas: "Areas (Features and Tasks)",
    errFieldsDiagnostics: "Fix the marked fields before running diagnostics.",
    errDiagnostics: "Diagnostics error",
    errFieldsConnection: "Fix the marked fields before testing the connection.",
    errAdoProjects: "Enter server, collection, and PAT to list projects.",
    errAdoTeams: "Enter server, collection, project, and PAT to list teams.",
    adoSelectAreas: "Select one or more areas...",
    adoNoAreasFound: "No areas found for this project.",
    errAdoLoadAreas: "Configure server, collection, project, and PAT to load areas.",
    errAdoLoadIterations: "Configure server, collection, project, and PAT to load iterations.",
    errImportInvalidJson: "Import error: invalid JSON file",
    confirmImportOverwrite: "Are you sure? This will overwrite all current data with the selected file's data.",
    writeSomething: "Write something",
    max2000Chars: "Maximum 2000 characters",
    invalidUrl: "Invalid URL",
    urlTooLong: "URL too long",
    mustBeLoggedIn: "You must be logged in",
    anonymous: "Anonymous",
    noteAdded: "Note added",
    noMatchingItems: "No matching items found.",
    // Not found
    pageNotFound: "Oops! Page not found",
    returnHome: "Return to Home",
    workloadAndCapacity: "Workload and Availability",
    allMembers: "All members",
    selectedCount: "{count} selected",
    searchMember: "Search member...",
    noResults: "No results.",
    weeks: "Weeks",
    nWeeks: "{count} Weeks",
    member: "Member",
    weekDate: "Week {date}",
    effortHours: "Effort: {hours}h",
    noTasksThisWeek: "No tasks assigned for this week.",
    filtersApplied: "Filters applied to Features and Tasks queries. Change them in Settings › Azure DevOps.",
    iterationsTasks: "Iterations (Tasks)",
    featureCount: "{count} feature",
    featuresCount: "{count} features",
    taskCount: "{count} task",
    tasksCountPlural: "{count} tasks",
    featuresOutOfArea: "Features out of area ({count})",
    tasksOutOfArea: "Tasks out of area ({count})",
    tasksOutOfIteration: "Tasks out of iteration ({count})",
    projectFeatures: "Project features",
    featureProgress: "Progress per feature with associated tasks",
    noFeaturesToShow: "No features to show.",
    tasksRatio: "{done} / {total} tasks",
    loadPerPerson: "Load per person",
    tasksPerPerson: "Tasks per person",
    fetchAreasError: "Could not read team areas: {error}",
    unassigned: "Unassigned",
    effectiveScope: "Effective scope",
    resultWithScope: "Result with this scope",
    noCustomScope: "No custom scope in Settings; using RODAT team defaults.",
    showingXofYFeatures: "Showing {x} of {y} features",
    showingXofYTasks: "Showing {x} of {y} tasks",
    excludedOutOfAreaFeatures: "Excluded: {count} out-of-area features,",
    excludedOutOfAreaTasks: " {count} out-of-area tasks,",
    excludedOutOfIterTasks: " {count} out-of-iteration tasks.",
    viewHiddenAudit: "View hidden items audit",
    area: "Area",
    iterationTasks: "Iteration (tasks)",
    expectedUnder: "Expected under {paths}",
    copyLinkTask: "Copy link for task {id}",
    copyLinkFeature: "Copy link for feature {id}",
    linkCopied: "Link for {type} #{id} copied",
    linkCopyFailed: "Failed to copy link",
    workDistribution: "Work distribution per person — only open and in-progress.",
    personCount: "{count} person",
    personsCount: "{count} persons",
    filtering: "filtering",
    inProgressPlural: "in progress",
    pendingPlural: "pending",
    blockedPlural: "blocked",
    completedPlural: "completed",
    confirmChangesBeforeApply: "Confirm changes before applying",
    unappliedChanges: "Unapplied changes",
    discard: "Discard",
    apply: "Apply",
    viewByPerson: "View by person",
    viewFlatList: "View flat list",
    showingMaxOf: "Showing {max} of {total} tasks — refine filters to see more.",
    noPersonsMatching: "No persons with tasks matching current filters.",
    allPersons: "All persons",
    allPersonsCount: "All persons ({count})",
    searchPerson: "Search person...",
  },
} as const;

type Translations = Record<keyof (typeof translations)["es"], string>;

interface LangState {
  lang: Lang;
  toggleLang: () => void;
  t: Translations;
}

const LanguageContext = createContext<LangState | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("teamflow-lang");
    return saved === "en" ? "en" : "es";
  });

  const toggleLang = () =>
    setLang((l) => {
      const next = l === "es" ? "en" : "es";
      localStorage.setItem("teamflow-lang", next);
      return next;
    });

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
